### PR TITLE
UI Content Package

### PR DESCRIPTION
**Pull request by conrad-vanl**
## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@redreceipt so this package all I've done so far is move components over to their own package. Next step is making changes in rest of app to point to these new components, and then we can start figuring out what's working and not working.

**Comment by redreceipt** [comment]
[Content](https://trello.com/c/Pb65u5VH/7-content)

**Comment by redreceipt** [comment]
@burkeshartsis @vinnyjth I did all of the suggested steps and am still getting the error on in the bundler.

**Comment by conrad-vanl** [comment]
I think a line needs to be added in `rn-cli.config.js` for this package:

https://github.com/ApollosProject/apollos-prototype/blob/master/packages/apolloschurchapp/rn-cli.config.js#L4

**Comment by redreceipt** [comment]
> I think a line needs to be added in `rn-cli.config.js` for this package:
> 
> https://github.com/ApollosProject/apollos-prototype/blob/master/packages/apolloschurchapp/rn-cli.config.js#L4

Added it, my sim is hanging up now.

**Comment by conrad-vanl** [comment]
What’s the hang up/error? Infinite loading screen? You should be able to get the error message to show by minimizing the app and opening the app drawer thing and see the error

**Comment by redreceipt** [comment]
> What’s the hang up/error? Infinite loading screen? You should be able to get the error message to show by minimizing the app and opening the app drawer thing and see the error

Can you explain in a little more detail on how to do that?

**Comment by redreceipt** [comment]
@conrad-vanl 
Screen Shot 2019-04-14 at 3 27 14 PM

**Comment by redreceipt** [comment]
@vinnyjth any ideas here? see build error above

**Comment by conrad-vanl** [comment]
@vinnyjth I did some work on this to get it up to latest master and building. I'm now getting the same error that @redreceipt is above.

It appears that any import from `ui-kit` isn't working. I tried a handful of different `package.json` arrangements, but haven't gotten anywhere. Ideas?

**Comment by conrad-vanl** [comment]
I'm officially FUBAR'ing this branch and we will re-address the merit of this work differently. Even if we get this branch working, it's not the right level of abstraction.

**Pull request closed without merging**
