### PR TITLE
Allow During Onboarding the Skipping of Birthdate, Gender, or Both

### PR DESCRIPTION
**Pull request by erikkgagewhitt**
### What does this PR do, or why is it needed?

Allows users to skip the birthdate, gender, or both fields when onboarding. I did this by slightly changing the form and mutation that manage these. The form now checks the values and dynamically builds the input to the mutation.

### What design trade-offs/decisions were made?

- The structure of the mutation on the client had to change since it was previously static
- Selecting "Prefer not to reply" will not actually save any data for gender, so it will be as if the user never input anything. This also means that changing from "male" or "female" to "prefer not to reply" will not actually change gender.

### How do I test this PR?

Best done on a new user

1. In onboarding with nothing selected, ensure that the user can skip
2. In onboarding, select "prefer not to reply"; no data should be saved
3. In onboarding, select a birthdate, but not a gender; you should advance and the birthdate should be saved.
4. In onboarding, keep your birthdate and select a gender; you should advance and your data should be saved

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@erikkgagewhitt I did some peeking in the codebase, and it looks like we do have a gender value for 'Unknown' 😬 

I would keep all the fantastic code you wrote around sending form values only as they are populated, and send over the gender as "unknown" if a user selects preferr not to say". That way if someonee unsets their gender it will actually be unset.

**Comment by vinnyjth** [comment]
https://github.com/ApollosProject/apollos-prototype/blob/master/packages/apollos-data-connector-rock/src/people/data-source.js#L82

**Comment by vinnyjth** [comment]
One more bug @erikkgagewhitt. "Unknown" doesn't seem to map back into "Prefer not to reply". if you select it in onboarding and then reopen onboarding.

**Comment by erikkgagewhitt** [comment]
@vinnyjth Do you mean that "Prefer not to reply' is unselected?

**Comment by vinnyjth** [comment]
Correct, when it should be selected.

**Comment by erikkgagewhitt** [comment]
Okay, yeah; I knew that happened - wasn't sure if it would be an issue. Should be easy to fix!

**Comment by erikkgagewhitt** [comment]
Initial value of 'Unknown' should work as intended now!

**Pull request merged**
