### PR TITLE
Try to implement our own onEndReached handler for StretchyView

### PR DESCRIPTION
**Pull request by vinnyjth**
## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by erikkgagewhitt** [comment]
@vinnyjth I think the code I pushed should get around the stretchy issue on Willow. Although, onScroll has to be a bit more explicit now.

**Comment by vinnyjth** [comment]
@erikkgagewhitt I like the code in this solution a lot :D Does it work? I don't mind the extra explicitness given what your other options are 😬

**Comment by erikkgagewhitt** [comment]
@vinnyjth I believe so! I tested in Willow first by directly modifying the package, then moved the code to core. I used a story to test it here, but that seems to be working.

**Comment by erikkgagewhitt** [comment]
@vinnyjth Although, Willow Creek will need to update their app to explicitly pass onScroll with the new signature.

**Comment by vinnyjth** [comment]
We ultimately won't need this :( Long term fix, if we ever need `onEndReached` in a `Stretchy` to work, will be to disable `useNativeDriver`

**Pull request closed without merging**
