### PR TITLE
Fix Featured Card Loading State

### PR DESCRIPTION
**Pull request by richarddubay**
### What does this PR do, or why is it needed?
This PR give a default loading state color to the `FeaturedCard`.

Screenshot 2019-11-26 07 56 07

### What design trade-offs/decisions were made?
It removes `theme.colors.primary` as the default loading state color. I used `theme.colors.lightSecondary` because the line color is `theme.colors.background.inactive` and I wanted the line to stand out from the background color.

### How do I test this PR?
Load the app and see the default loading state.

### What automated tests did you write?
None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@richarddubay so after checking out core design resources, it appears @kevin-birdy purposefully designed this card to have a primary color loading state:

image
https://www.figma.com/file/YeoeIuFfIiQmUAUFKEGwS6/Apollos-Core-UI-Kit?node-id=74%3A1671

Therefore, I need to get @kevin-birdy's sign off on this change. @kevin-birdy  - the issue we're running into is on both Willow Creek and NewSpring, the featured item has a dynamic color based on the content that is being featured. We don't know what that color is until after the item is loaded. So for example on the NewSpring app, during the loading state the featured card is the newspring green, then it might jump to a different color (depending on what content is currently featured). That can create a jarring experience. @richarddubay's suggestion was to use a different color for the loading state. What are your thoughts?

@richarddubay could you provide a screenshot of what the card looks like during loading in this PR?

**Comment by richarddubay** [comment]
Yep ... totally meant to put a screenshot. 🤦‍♂️

So this is what we currently see on the NewSpring app when the home feed is loading:
Screenshot 2019-11-26 07 53 44

As you can see, it uses our `theme.colors.primary` and that's great, if everything we had in the featured card was that color.

But now that we're using a dynamic `primary` color, once it finishes loading, it switches out to something like this:
Screenshot 2019-11-26 07 53 52

Which is quite different than the original `primary` color.

So what I'm proposing is something that more closely resembles the loading states everywhere else in the app:
Screenshot 2019-11-26 07 56 07

The color switch may still feel "jarring", but I don't feel like it's as big an issue since all the loading states do this.

Whatcha think?

**Comment by kevin-birdy** [comment]
Makes total sense! Let's just use `lightSecondary` so that these loading states match `HighlightCard` then.

Screen Shot 2019-11-26 at 9 37 55 AM

**Comment by richarddubay** [comment]
@kevin-birdy Sweet! `lightSecondary` was what I chose! 😍

**Comment by conrad-vanl** [comment]
@richarddubay are you able to make the text placeholders white? And would you know how we can drop the gradient during loading, to more closely match teh screenshot?

**Comment by richarddubay** [comment]
@redreceipt Do you think this is something that you could take over for me?

**Pull request merged**
