### PR TITLE
Updated Floating Input Label placement

### PR DESCRIPTION
**Pull request by asleepingpanda**
https://github.com/ApollosProject/apollos-prototype/issues/1018#issue-484616717

Moves the TextInput and FloatingLabel to a single container to keep the FloatingLabel from overlapping the Prefix and Suffix components

### What does this PR do, or why is it needed?
This keeps the Floating Label from overlapping the Prefix and Suffix which is needed to properly allow for design to be extended on the TextInputs

### What design trade-offs/decisions were made?
The Floating Label and TextInput sit inside of a wrapper so that the bounds of the Floating Label animation will never exceed the x/y, width/height or the TextInput. This means that anything added as a prefix will always act as a "padding" for the label and the label will sit flush with the left bound of the actual Text Box, not the left bound of the entire Text Input object. (it'll make more sense when you actually interact with the Stories)

### How do I test this PR?
Stories were added to show the visual changes

### What automated tests did you write?
Updated snapshots

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by burkeshartsis** [comment]
@asleepingpanda did you see @conrad-vanl comment above?

**Comment by asleepingpanda** [comment]
@burkeshartsis those updates per the comment from @conrad-vanl is good to go! I didn't realize there was a merge conflict, but it's been resolved.

**Comment by burkeshartsis** [comment]
@asleepingpanda looks like you still have some failing tests. See @conrad-vanl's comment [here](https://github.com/ApollosProject/apollos-prototype/pull/1019#pullrequestreview-279152482) for direction.

**Comment by asleepingpanda** [comment]
@burkeshartsis I updated thee snapshots that are relevant to this update. I did notice that there is a Redis test failing, although nothing about this branch's updates has to do with Redis.

Anyway, I can't tell anything else that needs to be done on this, just let me know and I'll try to get it wrapped up. This has been sitting here for a while and I would really like to get this finished asap, so just let me know if anything else is needed! Thank youuuuu

**Pull request merged**
