### PR TITLE
Exports ContentItemInterfaceFields and document usage

### LINKED ISSUE #755: Export the ContentItem interface fields.
### User Story

As a creator of a new ContentType I should be able to import the base `interface` fields from `server-core`.

### Description
Doing this will make it easier to create new implementations of `ContentItem` and also make sure that clients that upgrade to new versions of the schema with a new implementation get the new fields. 

### Acceptance Criteria

* [ ] Export the base fields used in the `ContentItem` `interface`
* [ ] Also use that new variable to define all of our existing ContentItems. 

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

### PR DESCRIPTION
**Pull request by vinnyjth**
### What does this PR do, or why is it needed?

As a developer, it's obnoxious to need to include the ContentItem interface fields every time you extend the interface. If we export those fields as a variable, we can give a mechanism by which developers can include all the fields on the interface without needing to copy/paste them. 

This will also make upgrading to new versions of the `ContentItem` interface easier. 

### What design trade-offs/decisions were made?

`MediaContentItem` and `SeriesContentItem` support Scripture, but don't actually fetch scripture. I fixed that in this PR. 

### How do I test this PR?

1. Download this PR.
2. Run this PR
 - Your server will crash if the new schema is invalid. 

### What automated tests did you write?

n/a

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes #755
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by calebpanza** [comment]
@conrad-vanl that makes a lot sense to split it up per that modularization branch. At the end of the day, the current problem that is being faced is that the `ContentItem` interface is quite large and when developing on top of the interface, it's very easy to miss attributes in the schema. If the modularization would help solve that issue, my vote would be that we follow through with that sooner rather than later in order to help set up the dev environment for the churches.

**Comment by vinnyjth** [comment]
>How would you feel if I worked on a less but better version of the schema modularization PR? Basically just splitting our current ContentItem interface up into a few smaller interfaces:

I would much prefer this approach, but I don't think it solves @calebpanza's issue. He will still have to list the fields from all the different extensions he implements. 

@calebpanza I think the best answer we can give you in the short term is "learn to read the error messages :P" GraphQL will give you pretty good error messages about what fields are missing, which should help when copy and pasting new fields to your implementation. I like the idea of including fields from a variable, but @conrad-vanl Is totally right, it's a pretty unique and unorthodox way to approach building a schema.

**Comment by calebpanza** [comment]
@vinnyjth the problem isn't knowing what the error is. It's 10000% a convenience problem. For example, on one of our projects, we've got 2 or 3 data types that extend the `ContentItem`. When an update is pushed to Apollos Core, our resolvers & data sources will be all good to go when we update our version number cause they import and inherit from Core, but we will have to go into the Core Project to manually find and copy the new schema into each of our other schemas. For convenience sake, it would be nice if Core schemas could be imported since the Resolvers and DataSources already do. 

So I've read through [this](https://graphql.org/learn/schema/#interfaces) documentation a few times, and I notice that their example keeps the schemas down to a _very_ small number of properties. @conrad would it be "dangerous" or super far outside of Graph's conventions to import schemas so long as those schemas were very, very small in nature?

**Comment by conrad-vanl** [comment]
This is a great conversation.

@vinnyjth would there be a way to do this with a schema directive? I'm not sure I like that _much_ better, but at the least, it's a little more extensible as we could make a directive that would work anywhere on the graph, instead of having to piece-meal strings and export them manually.

**Comment by vinnyjth** [comment]
> would there be a way to do this with a schema directive? I'm not sure I like that much better, but at the least, it's a little more extensible as we could make a directive that would work anywhere on the graph, instead of having to piece-meal strings and export them manually.

I remember looking at this a while back, and I think what I determined was that Schema Directives can change how a schema functions, but not the shape of a schema :/

**Comment by conrad-vanl** [comment]
I just can't help but feel that exporting these strings like this is a code smell. Again, I'm not opposed to go ahead and doing it, especially since I can't well articulate what's so bad about it, other then it goes against GQL convention.

**Comment by vinnyjth** [comment]
> I just can't help but feel that exporting these strings like this is a code smell.

I agree with this. 

@calebpanza I'm going to put this on hold for the time being. I have another idea that I will explore with you to make this easier soon :) This approach is a little too heavy handed and far from GQL convention from my taste.

**Comment by calebpanza** [comment]
@vinnyjth @conrad-vanl makes a lot of sense! And perhaps at the end of the day, maintaining smaller updates to specific fragments will prove to be not as daunting and still live within the proper boundaries of GQL implementation. I like that approach and would love to work out whatever solution you guys are thinking of if you're up for it!

**Pull request closed without merging**
