### PR TITLE
Adds Family/Location API

### PR DESCRIPTION
**Pull request by vinnyjth**
Fixes [issue-number]

## Creator

- [ ] Build relevant tests if any apply
- [ ] Ensure there are no new warnings (in app AND in storybook)
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [ ] Set a relevant reviewer
- [ ] PR has a relevant title that adheres to our patch-notes/change-log style

## Reviewer

- [ ] Review CI build results
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [ ] Review new stories if any apply
- [ ] Review test coverage: Are all new or changed states tested?
- [ ] Review new test logic
- [ ] Review that the PR title adheres to our patch-notes/change-log style

### CODE REVIEW

**Comment by IsaacHardy** [comment]
@vinnyjth I see you are using `extend type Person` on the schema. Can you think of a reason why the GraphQl Playground doesn't recognize the value as part of the `Person` schema?

**Comment by vinnyjth** [comment]
@IsaacHardy Hmm, not having the trouble locally. What error are you getting?

**Comment by IsaacHardy** [comment]
screen shot 2018-10-02 at 1 11 43 pm

**Comment by vinnyjth** [comment]
Does the query run? Not seeing the red underline locally.

**Comment by IsaacHardy** [comment]
screen shot 2018-10-02 at 1 12 27 pm

**Comment by IsaacHardy** [comment]
@vinnyjth Everything runs great. Just doesn't recognize the schema on playground.

**Comment by vinnyjth** [comment]
@IsaacHardy No idea. Can't reproduce.

**Comment by IsaacHardy** [comment]
After Closing the tab and reopening the playground in a new one, it worked!

Approved!

**Pull request merged**
