### PR TITLE
Adds Thumbnails

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

Screen Shot 2019-11-19 at 2 19 31 PM

### What does this PR do, or why is it needed?

Adds `thumbnailImage` to content items so we can show them instead of series artwork in the app.

### What design trade-offs/decisions were made?

None.

### How do I test this PR?

Bring up the "Gathering" series, you should see the "Spur One Another" sermon have a thumbnail.

### What automated tests did you write?

None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [#901]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@redreceipt Help me understand this: why not use the cover images? Do you want the cover image to always show the series image, and then be able to show a different image inside the horizontal card view?

**Comment by vinnyjth** [comment]
Here's what I see in core right now
image

**Comment by redreceipt** [comment]
I would assume we'd want the artwork on the content single header and save the thumbnails for the "Play" button and the horizontal tile list.

@kevin-birdy have thoughts on needing thumbnails and series artwork?

**Comment by vinnyjth** [comment]
@redreceipt Yah, I would be curious to know what @kevin-birdy thinks about needing two images for cards. For now @redreceipt you might be better off doing this in your own app.

**Comment by redreceipt** [comment]
Actually I don't think we do now that I think about it. Client side, you could either show the `coverImage` or the parents `coverImage`

**Comment by vinnyjth** [comment]
Yep :D So I think we are good here. Feel free to reopen if I'm wrong.

**Comment by conrad-vanl** [comment]
FWIW, while i'm not sure this PR is the right way to go about it, I do think a secondary image in our schema might be beneficial. and `thumbnailImage` might be the right way to think about it - essentially we're learning that our ui has two use cases for images - one where the image is presented big and boldly, and the other where it's presented small with text laid on top of it. It is hard to produce images that work well for both use cases.

**Comment by kevin-birdy** [comment]
seconding @conrad-vanl 's comments. It's basically impossible to have a catch-all solution, so two images provides some flexibility that will prove useful.

One other thing I want to add on to this. It might be a separate issue but it feels the same. For video content items, having a `thumbnailImage` would be great because then we wouldn't have two of the same images stacked on top of each other.

**Comment by redreceipt** [comment]
yes and yes, but the question is couldn't we just use the parent's cover image as the artwork and the sermon cover image as the thumbnail?

**Comment by redreceipt** [comment]
...unless you would ever want a sermon series to have a trailer or something

**Comment by redreceipt** [comment]
> One other thing I want to add on to this. It might be a separate issue but it feels the same. For video content items, having a `thumbnailImage` would be great because then we wouldn't have two of the same images stacked on top of each other.

@conrad-vanl this is why I thought it might be good to have a `videos.thumbnail` field instead of a `ContentItem.thumbnailImage` field

**Comment by kevin-birdy** [comment]
Does every sermon have a parent? As far as sermons go that makes a lot of sense to me. Also probably means that it is in fact a slightly different discussion. How it gets implemented is up to you guys. I am all for the value of a `thumbnailImage` though.

**Comment by conrad-vanl** [comment]
Yes, you could use the parent and in that case I would want you to point the items coverImage to the parent item. You shouldn’t do that mapping on the client.  It sounds like we all agree content items need two images, at the least. Our schema does not support that clearly - it only has the one coverImage. @vinnyjth we should add this as a Validated feature request somewhere. Not something we need to implement immediately but something we should handle on core.

**Comment by redreceipt** [comment]
I think a better solution is a key/value pair for videos in Rock:

```
videoUrl: video.mp4
thumbnailUrl: image.jpg
```

That's what wistia gets us and I got it working on our app last night with a very simple schema.

**Comment by redreceipt** [comment]
that way you could have a separate thumbnail for every video on the content

**Comment by redreceipt** [comment]
or else we probably shouldn't have `videos` be an array

**Pull request closed without merging**
