### PR TITLE
Adds Index to Paginated Content

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

Screen Shot 2019-11-18 at 3 21 11 PM

### What does this PR do, or why is it needed?

Simply adds an `index` field to `ContentItemsConnectionEdge` so you know where in the full list you are. Useful for lots of things.

### What design trade-offs/decisions were made?

None.

### How do I test this PR?

```
{
  userFeed(after:"7c613b3d35342b1bb0c53c1089ac11c6") {
    edges {
      cursor
      index
      node {
        title
      }
    }
  }
}
```

### What automated tests did you write?

None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
You're going to have to sell me on this field, I don't see the utility.

**Comment by conrad-vanl** [comment]
@vinnyjth they want to be able to add the number of an item in the horizontal content feeds. Like the current app has a little number on each tile in the horizontal content feeds indicating which number that item is in the series

**Comment by conrad-vanl** [comment]
my worry would be rather this is something that is feasible on large lists

**Comment by conrad-vanl** [comment]
dang, don't accidentally hit "close and comment" instead of "comment", mergify will lay down the law!

**Comment by redreceipt** [comment]
yea it wouldn't be used on big lists. it could I guess and there would be no performance hit if you did.

**Comment by redreceipt** [comment]
> You're going to have to sell me on this field, I don't see the utility.

"Week 1 of 7"

**Comment by vinnyjth** [comment]
I think I would prefer if this was implemented as a `seriesInfo: String` field on the `ContentItem`. Thoughts on that @conrad-vanl?

**Comment by vinnyjth** [comment]
@redreceipt https://facebook.github.io/react-native/docs/flatlist#renderitem `renderItem` passes an Index. I would use that if you're rendering the devotional number. At this point we never fetch the "last 20 devotionals". We always fetch the first 20, and then paginate further as a user scrolls.

**Comment by redreceipt** [comment]
> @redreceipt https://facebook.github.io/react-native/docs/flatlist#renderitem `renderItem` passes an Index. I would use that if you're rendering the devotional number. At this point we never fetch the "last 20 devotionals". We always fetch the first 20, and then paginate further as a user scrolls.

I want to put "Week 4" on the sermon notes too, doesn't use flatlist

**Comment by redreceipt** [comment]
oh but i suppose i could still pass in as a prop

**Comment by redreceipt** [comment]
...wait no, not if it was a campaign item

**Comment by redreceipt** [comment]
so i thought about doing it on `ContentItem` but the paginated field seemed much more multipurpose and *much* simpler

**Comment by vinnyjth** [comment]
If you do it on the pagination the index will be wrong (won’t reflect the week) on the featured item (and everywhere else)

**Comment by redreceipt** [comment]
Yea, you’re right. It should totally be `contentItem.seriesIndex`, similar to my `series` field. If core doesn’t want this one either, you can close, I’ll just put it in NewSpring code.

—
Michael

**Comment by vinnyjth** [comment]
Core would love the ability to tell which week / index an item is, with in a series, I just want to make sure we use the best approach possible to do that :)

**Comment by redreceipt** [comment]
> Core would love the ability to tell which week / index an item is, with in a series, I just want to make sure we use the best approach possible to do that :)

Do you not think it goes hand in hand with merging #1025?

**Comment by redreceipt** [comment]
closing this, it's not the right strategy, we can continue the convo in #1022

**Pull request closed without merging**
