### PR TITLE
Adds Rock Token to API

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

Screen Shot 2019-10-07 at 3 02 40 PM

### What does this PR do, or why is it needed?

This adds the Rock impersonation token to our API which allows for logging into external sites via URL parameters rather than cookies.

### What design trade-offs/decisions were made?

None.

### How do I test this PR?

```
{
  currentUser {
    rockToken
    rock {
      authCookie
      authToken
    }
  }
}
```

### What automated tests did you write?

None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
before we merge, we may want to add an expiration to the token. or that can be a separate PR.

**Comment by vinnyjth** [comment]
Very nice, can you write me some tests please?

**Comment by vinnyjth** [comment]
Thanks for adding tests!

**Comment by redreceipt** [comment]
no problem, the only chunk I left out was the temporary section that will be removed once Rock v10 is standard

**Comment by richarddubay** [comment]
@redreceipt If you can fix the tests that are failing here, we can get this one in and be one step closer!

**Pull request merged**
