### PR TITLE
Notifications hasPrompted State

### PR DESCRIPTION
**Pull request by erikkgagewhitt**
### What does this PR do, or why is it needed?

Handles the state where the user has already been prompted for notifications and has declined. I previously tried [this](https://github.com/ApollosProject/apollos-prototype/pull/1243), but found that I could not enable notifications, if a user had ever declined them (makes sense from a user protection standpoint, but is very obnoxious). I also tried using listeners, but to no avail.

Now instead, I disable the notifications button to show the choice has already been made; I disable the"skip" button and enable the "finish" button 

### What design trade-offs/decisions were made?

Not sure this solution is great design-wise, but it seemed to look alright and make sense to me.

### How do I test this PR?

1. Delete the app from your sim
1. In onboarding tap Enable Notifications and reject the hard ask
2. Log out
3. In onboarding the state of this screen should change

## SCREENSHOTS

Screen Shot 2019-11-21 at 3 47 54 PM

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by erikkgagewhitt** [comment]
@vinnyjth Not quite as good, but fixes the same issue as https://github.com/ApollosProject/apollos-prototype/pull/1243 did

**Comment by vinnyjth** [comment]
@burkeshartsis can you comment on the flow of this PR vs how you imagined the final flow?

**Comment by conrad-vanl** [comment]
@erikkgagewhitt @vinnyjth I think I could be okay with this but we need to chnage the button text to communicate to user why it's disabled. +1 would be some help text going into more detail with a link that opened up settings.

@erikkgagewhitt do we know for sure in this case that notifications are disabled? IF so, I think MVP approach would be:

> Notifications disabled in settings

With a +1 Helptext added somewhere that says like:

> Open **settings** and navigate to APP_NAME to enable notifications

**Comment by vinnyjth** [comment]
@erikkgagewhitt I would go ahead and make the changes @conrad-vanl Suggested to this PR before we merge :D

**Comment by erikkgagewhitt** [comment]
@vinnyjth Button text added!

**Comment by vinnyjth** [comment]
@erikkgagewhitt I'm testing this by building for Testflight (best way I've found to genuinely test notification setup) 

https://appcenter.ms/orgs/Apollos-Church/apps/Apollos-Church/build/branches/notifications-prompted-state/builds/712

**Comment by erikkgagewhitt** [comment]
I just want to quickly layout my plan. I'm going to try my hand at a Provider/Consumer approach; hopefully this will fix the issues with cached data.

There are still some other issues you mention and I'm not sure this approach will fix them on its own. The issue is OneSignal subscriptions. I can find no way to reenable them after a user has disabled them. Even the user turning notifications back on does not enable subscriptions.

To fix these issues, I'd like to use the Permissions package to handle notifications permission. If a user rejects notifications, we will manually disable the subscription (this is the only method that can be reversed of disabling a subscription). We should then be able to use a Onesignal permission listener to manually enable/disable subscriptions as the user changes their settings.

**Comment by erikkgagewhitt** [comment]
@vinnyjth I've not messed with a context/provider format before; when I do this, will I keep the same queries that we have now? It seems like I would, but I just want to make sure.

**Comment by vinnyjth** [comment]
@erikkgagewhitt 
> I've not messed with a consumer/provider format before; when I do this, will I keep the same queries that we have now? It seems like I would, but I just want to make sure.

I think you can go either way :) I think one of the issues we are seeing is that the queries don't ever rerun against the resolvers, so you might run into issues if you try and use the queries as the backbone for the provider. I don't care either way, whatever you think produces the cleanest and most functional API I'm good with!

**Comment by erikkgagewhitt** [comment]
Closed in favor of https://github.com/ApollosProject/apollos-prototype/pull/1266

**Pull request closed without merging**
