### PR TITLE
Removes Redis warnings and fixes cache keys for like counts

### PR DESCRIPTION
**Pull request by vinnyjth**
### What does this PR do, or why is it needed?

- Changes the way Redis is loaded, so that it's only loaded if the REDIS_URL is set, and gives nice warnings if it's not (but only when the redis cache is used) 
- I never fixed some of the cachekeys on the server, so `likedCounts` weren't being cached correctly. Woops! 

### What design trade-offs/decisions were made?

n/a

### How do I test this PR?

Run the app with a `REDIS_URL` set in your .env and load the home feed, you shouldn't see any warnings. 
Run the app without a `REDIS_URL` set in your .env and load the home feed, you should see a number of warnings, but only when loading the home feed.

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
I don’t have redis installed and do not have the variable defined and am hung up on build here

Screen Shot 2019-10-09 at 1 37 16 PM

**Comment by redreceipt** [comment]
Works without it. there's still a couple of ugly warning right when you `yarn start` but not during app execution anymore.

What's the `REDIS_URL` that I can test with?

**Comment by vinnyjth** [comment]
`redis://localhost:6379`

**Comment by redreceipt** [comment]
didn't get any warnings when loading the home feed, how can I verify redis is working properly?

**Pull request merged**
