### PR TITLE
Create MediaPlayer package

### PR DESCRIPTION
**Pull request by conrad-vanl**
## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@redreceipt so this package all I've done so far is move components over to their own package. Next steps are updating existing components in `apolloschurchapp` to reference the new moved components. Then for this package we need to figure out how to handle state. That part is something we might have to sync up on.

**Comment by redreceipt** [comment]
... or do we want to upgrade to RN 59 and make this our first foray into hooks :)

**Comment by redreceipt** [comment]
[MediaPlayer](https://trello.com/c/AE8dLoVO/9-mediaplayer)

**Comment by vinnyjth** [comment]
@conrad-vanl Can you give this a once over?

**Pull request merged**
