### PR TITLE
Removes KeyboardAwareScrollView Package

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

Removes `react-native-keyboard-aware-scrollview` because it's causing problems with upgrading to RN 59. Plus one less dependency 🙌 

### What design trade-offs/decisions were made?

None visible that I can tell.

### How do I test this PR?

- [ ] Check PersonalDetails
- [ ] Check ChangePassword
- [ ] Auth/Signup Form
- [ ] Auth/Login Form

### What automated tests did you write?

None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@redreceipt Without diving into this PR myself, what implications on the experience have you found as a result of this PR? Do the fields on the Login/Signup page still scroll up to avoid the keyboard on both iOS and Android? 

I'm all for removing this package - but we need to make sure we have something to replace the existing UX first.

**Comment by redreceipt** [comment]
From what I can tell nothing has been lost. On the auth pages, the button still scrolls up with the keyboard. On the user pages, they never did. Can't figure out why but that's another issue.

**Comment by vinnyjth** [comment]
@redreceipt Awesome. I'll run through this myself shortly. This would be a great PR to include a gif or two.

**Comment by vinnyjth** [comment]
Lol, I just realized you made twice the changes I did in this PR: https://github.com/ApollosProject/apollos-prototype/pull/733/files

**Pull request merged**
