### PR TITLE
Adds spacing to miniplayer controls

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

Screen Shot 2019-09-03 at 8 30 43 AM

### What does this PR do, or why is it needed?

The miniplayer icons were too close together. This fixes that.

### What design trade-offs/decisions were made?

Didn't surround the icons with 24px exactly, that was making the title too small. Instead I just `flex/space-evenly`'d the icons and made the ratio for title to icons 2:1.

### How do I test this PR?

Bring up the miniplayer on different device sizes.

### What automated tests did you write?

None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [#1011]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [x] Manual QA on iOS and ensure it looks/behaves as expected
- [x] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [x] Read through the "Files changed" tab _very carefully_
- [x] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [x] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
@kevin-birdy Ok here's 24 exactly, better?

Screen Shot 2019-09-04 at 10 59 55 AM

**Comment by kevin-birdy** [comment]
@redreceipt Soooo I'm having trouble figuring out exactly what's going on, but the original space-around implementation actually looked a lot closer to Sketch than this latest screenshot.

If anything...I guess I would vote for us sticking with that. Hope that doesn't confuse things further.

Screen Shot 2019-09-04 at 1 10 14 PM

**Comment by redreceipt** [comment]
maybe @burkeshartsis has some insight??? I'm trying to make it 24px exactly but that seems to be too much and not match the sketch mock.

**Comment by kevin-birdy** [comment]
Honestly what you had before looked pretty solid ☝️

**Comment by redreceipt** [comment]
> Honestly what you had before looked pretty solid ☝️

Ok cool, before we move forward, I'd still like to understand from @burkeshartsis where the gap may be, for future work if anything.

**Comment by kevin-birdy** [comment]
@burkeshartsis this is what I have right now and I would argue it's too close/small. The screenshot I posted above ("Video Title" vs. "Money Wise") I think provides a friendly tappable area. That's my only concern.

IMG_F33AC56D8E66-1

**Comment by redreceipt** [comment]
@kevin-birdy @burkeshartsis how's this?

Screen Shot 2019-09-22 at 2 50 40 PM

**Comment by kevin-birdy** [comment]
I like this a lot more @redreceipt

**Pull request merged**
