### PR TITLE
Fixes MiniPlayer Safe View

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

Screen Shot 2019-09-01 at 2 45 27 PM

### What does this PR do, or why is it needed?

The mini-player (and probably some other stuff) is too close to the bottom for our liking. This replaces the `react-native/SafeAreaView` with the one from `react-navigation`

### What design trade-offs/decisions were made?

Pretty substantial snapshot change but I double-checked a few screens and I think we're better for it. Seems `react-navigation` uses `View`'s in places that `react-native` didn't.

### How do I test this PR?

Pull up the miniplayer and behold.

### What automated tests did you write?

None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [#1012]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
`react-navigation/SafeAreaView` is breaking some tests. They are failing in the `ui-kit` because of this error: 

Screen Shot 2019-09-01 at 3 30 22 PM

Any thoughts?

**Comment by redreceipt** [comment]
And just FYI, the reason all the snaps are changing is simply that the `LayoutProvider` is in pretty much in all of our tests.

**Comment by redreceipt** [comment]
https://github.com/facebook/jest/issues/3707

**Comment by vinnyjth** [comment]
I would be happy to merge this if we can get tests to pass.

**Comment by redreceipt** [comment]
...yea I'm trying. The `Picker` `autoFocus` prop is calling `findNodeHandler` (or something like that). Trying to mock it to delete that prop entirely but I'm playing with stuff I don't fully understand :)

**https://github.com/facebook/jest/issues/3707**

**Comment by burkeshartsis** [comment]
>  This replaces the react-native/SafeAreaView with the one from react-navigation

@conrad-vanl this may very well be the correct solution but is it the solution we want? If I remember correctly we are trying to not have to rely on `react-navigation`'s version of this component correct?

**Comment by conrad-vanl** [comment]
Unfortunately it seems that `react-native`'s `SafeAreaView` doesn't seem to work most of the time. Not sure if it's an issue with `react-native-screens` or `react-navigation` or just a bug in `react-native`. Eitherway I support using this, unfortunately.

**Comment by redreceipt** [comment]
...now that all eyes are on this, anyone wanna help me fix the tests??? The `Picker` autoFocus prop is screwing it up somehow.

**Comment by conrad-vanl** [comment]
I know we need to figure out tests but finally got around to clicking the "approve" button. Travis will keep us honest on tests though. 

@redreceipt I wonder if just adding a mock for React-Navigation's `SafeAreaView` would fix tests?

**Pull request merged**
