### PR TITLE
Fixes Android Campus Card Shadow

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

Screen Shot 2019-06-30 at 4 47 59 PM

Screen Shot 2019-06-30 at 4 47 32 PM

### What does this PR do, or why is it needed?

Android was clipping the campus card shadow because it was too wide. This fixes that. I also greatly simplified the `ui-kit/CampusCard` implementation and moved some of the weird hardcoding logic we're doing into the `MapView` (to be fixed at a later date 😉).

### What design trade-offs/decisions were made?

Removed the need for some libraries.

### How do I test this PR?

Go through onboarding in both Android and iOS.

### What automated tests did you write?

None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [#773]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
Pic of campus card without image 👍 
image

**Comment by vinnyjth** [comment]
A very solid refactor that cleans up the code AND results in a better visual experience. @redreceipt fix the tests and I'll merge!

**Comment by redreceipt** [comment]
I can't tell why this test is failing...

**Comment by redreceipt** [comment]
it passes locally

**Comment by vinnyjth** [comment]
@redreceipt Something is weird with your local setup, the snapshots you pushed were incorrect I think.

**Comment by redreceipt** [comment]
daaaang it. I need to understand that. which snapshots were bad?

**Comment by vinnyjth** [comment]
@redreceipt `UserAvatarHeader` stood out to me, looks like that's where most of the non correct differences were.

**Comment by redreceipt** [comment]
weird, on this one, it looks like `<Image>` should be nested inside of `<View>` but my computer made them siblings...

Screen Shot 2019-07-02 at 11 25 51 AM

**Pull request merged**
