### PR TITLE
Order Rock data by multiple fields

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

This allows us to order by multiple fields in OData like this:

`PrayerCount asc, EnteredDateTime asc`

### What design trade-offs/decisions were made?

Deprecates old `orderBy` function as to not introduce any breaking changes.

### How do I test this PR?

Replace one of the `orderBy` cursors with the new `sort` function using multiple fields.

### What automated tests did you write?

None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
I like this change, I'll give it a review sometime next week and merge it :) 

In the meantime, you can do what you want to do by doing `.orderBy('PrayerCount asc, EnteredDateTime asc', '')`

**Comment by vinnyjth** [comment]
Also I need tests before I can merge this ;)

**Comment by redreceipt** [comment]
> Also I need tests before I can merge this ;)

Done.

**Comment by vinnyjth** [comment]
Nice work @redreceipt, thanks for your hard work!

**Pull request merged**
