### PR TITLE
HTMLVideoPlayer

### LINKED ISSUE #139: Video in content items
## User Story

A user can watch media attachments on content items. Ex: the sermon video for a specific sermon content item.

#### Problem Details _(Optional)_

* Display a `<WebView />` with the `embedCode` for a video supplied from the graphql api
* Add example videos to content already in Rock

#### Acceptance Criteria _(Optional)_

* [ ] A user can watch a video in app and it feels like a native experience
* [ ] The video is shown instead of the content `coverImage` on the `content-single` view

### PR DESCRIPTION
**Pull request by conrad-vanl**
## Creator

- [x] Build relevant tests if any apply
- [x] Ensure there are no new warnings (in app AND in storybook)
- [x] Upload an animated GIF showcasing the solution (if it applies)
- [x] Set a relevant reviewer
- [x] Add a line to the changelog documenting the high-level change this PR introduces

image

## Reviewer

- [ ] Review CI build results
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [ ] Review new stories if any apply
- [ ] Review test coverage: Are all new or changed states tested?
- [ ] Review new test logic
- [ ] Review the changelog entry

### CODE REVIEW

**Comment by conrad-vanl** [comment]
This is essentially ready. However, if we have time in this sprint, I'd like to look into improving, so gonna leave open for now.

**Comment by IsaacHardy** [comment]
@conrad-vanl I'm having difficulties running this branch after the newest master branch was merged. I'm getting this: 

screen shot 2018-07-24 at 1 22 12 pm

**Comment by IsaacHardy** [comment]
@conrad-vanl Could you give me an example of a working video? I cannot seem to find one. Receiving blank white display where a video might be.

**Comment by conrad-vanl** [comment]
@IsaacHardy the first sermon in the feed, "The Greatest Evangelist" should have a video on it, like the screenshot at the top

**Comment by conrad-vanl** [comment]
but maybes omething with the react-native upgrade messed it up 🤔

**Comment by IsaacHardy** [comment]
@conrad-vanl Seems like the only video that is working is the one displayed above. I receive that white blank spot with every other sermon page.

**Comment by IsaacHardy** [comment]
Possibly that it recognizes the video html is present, but never displays it. (gets rid of GradientOverlayImage)

**Comment by conrad-vanl** [comment]
🤔 that is the only sermon with a video currently, but the other ones should show the image

**Comment by conrad-vanl** [comment]
@IsaacHardy the other sermons seem to be loading the image for me. Which sermon are you seeing that's displaying a blank box?

**Comment by IsaacHardy** [comment]
@conrad-vanl When I tested, it was every sermon.

**Comment by burkeshartsis** [comment]
The sermon in the screenshot form @conrad-vanl does not display a video for me 😢 

simulator screen shot - iphone x - 2018-07-26 at 17 09 47

**Comment by conrad-vanl** [comment]
I wonder if it's a `fetchPolicy` / caching thing 👀

**Comment by conrad-vanl** [comment]
After considering this over the weekend and end of last week, I believe two things are true:

1. The video platforms used by our initial partner churches are very diverse, which makes a non-web-based integration tough
2. Web-based videos suck, especially on Android (even if we get the player working correctly on Android, it'll likely not support all features, like full-screen video).

My question: what's our best solution?

It seems like most of the video providers are:

1. Youtube
2. Wistia
3. StreamMonkey
4. Haivision

**Comment by burkeshartsis** [comment]
At this point we have not found a meaningful solution we feel comfortable proceeding with. This PR is being closed without merge due to Android just not working and with the knowledge that getting it to work is a compromise to begin with and any change in provider will likely break the implementation. We will be opening new PR's to address this with a native video solution.

**Pull request closed without merging**
