### PR TITLE
Prevent Extra Space in Tab Bar

### PR DESCRIPTION
**Pull request by erikkgagewhitt**
### What does this PR do, or why is it needed?

Prevents extra space from appearing in the tab bar. It was possible to see the tab bar in a state where there was significantly more space above the icons than is intended. We prevent this by changing the safeAreaInset prop passed to TabBar to force the top inset to be 0.

It was also necessary to swap out the react-navigation SafeAreaView in the MediaPlayerSpacer component with the SafeAreaView from react-native. This was because the react-navigation version adds additional spacing to the top of the component for as-of-yet undetermined reasons.

### How do I test this PR?

You can reproduce this bug consistently in master by adding the following line to any file changed in this PR (or really anywhere):

`console.disableYellowBox = true;`

Do the same on this branch and you should see the TabBar at the correct size.

## SCREENSHOTS

|Before|After|
|---|---|
|Screen Shot 2019-10-03 at 3 42 37 PM|Screen Shot 2019-10-03 at 3 34 34 PM|

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@erikkgagewhitt This is awesome, and like 99% there! 

I found an issue with the media player however. We recently fixed the media player padding, so that the media player wasn't so close to bottom notch. However, one of the changes in this PR reverts the fix. I've attached a picture below of `master` and of your branch. 

| Master | This Branch |
|--------|-------------|
|   Screen Shot 2019-10-04 at 11 28 54 AM |  Screen Shot 2019-10-04 at 11 28 17 AM  |

**Comment by erikkgagewhitt** [comment]
Thanks for calling that out @vinnyjth

**Comment by erikkgagewhitt** [comment]
@vinnyjth It's interesting, but neither reverting my changes nor switching to master seem to fix this for me.

**Comment by vinnyjth** [comment]
Closed in favor of #1095. Nice work @erikkgagewhitt!! Really impressed with how close you came to solving this issue.

**Comment by vinnyjth** [comment]
@erikkgagewhitt Can you test this and make sure the spacing issue above is fixed with this PR? If not, we can figure some way to get this merged.

**Comment by erikkgagewhitt** [comment]
@vinnyjth Are you referring to the media player touching the notch?

**Comment by vinnyjth** [comment]
Yep! Thanks for clarifying.

**Comment by erikkgagewhitt** [comment]
@vinnyjth Can confirm that the spacing looks alright

Screen Shot 2019-10-21 at 11 12 26 AM

**Comment by vinnyjth** [comment]
Yout the 💣 :D I'm not sorry for merging this earlier, that's all on me for not seeing the value of this.

**Comment by erikkgagewhitt** [comment]
It's all good! It's a weird "fix" and it seems like something we shouldn't have to do.

**Pull request merged**
