### PR TITLE
Optimizes Live Stream Query

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

This removes `liveStream` from the `getContentItem` query because it's cached on a much lower TTL. Also Removes all the content item parts from the `getContentMedia` query so it stays in sync with the content single. All that is just passed in as props now.

### What design trade-offs/decisions were made?

None.

### How do I test this PR?

Pull up some different content items with and without the live stream going.

### What automated tests did you write?

None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
this will probably change after merging #1086

**Comment by redreceipt** [comment]
@vinnyjth this one is ready now

**Comment by vinnyjth** [comment]
@redreceipt Love this PR, but let's keep the `getContentMedia` query for now. I think we could look at making sure that data matches the data inside the `getContentSingle` query that is run for the whole card so that we never query the API for this data.

**Comment by vinnyjth** [comment]
@redreceipt I'll wrap up this PR :)

**Comment by redreceipt** [comment]
> @redreceipt Love this PR, but let's keep the `getContentMedia` query for now. I think we could look at making sure that data matches the data inside the `getContentSingle` query that is run for the whole card so that we never query the API for this data.

that's the part of apollo client I don't understand yet

**Pull request merged**
