### PR TITLE
Create Scripture Package

### PR DESCRIPTION
**Pull request by conrad-vanl**
## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@redreceipt so this package all I've done so far is move components over to their own package. I think I s tarted updating existing components to point to the new scripture components, but I believe I was running into some bugs

**Comment by redreceipt** [comment]
[Scripture](https://trello.com/c/04nJER1w/8-scripture)

**Comment by vinnyjth** [comment]
Blocked by #737

**Comment by vinnyjth** [comment]
This is looking good!

**Comment by vinnyjth** [comment]
image
image

**Pull request merged**
