### PR TITLE
updated to v0.4.0

### PR DESCRIPTION
**Pull request by IsaacHardy**
Updating app and api versions to v0.4.0.

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@IsaacHardy starting with 0.4.0, you want to remove the changelog.md file in favor of just keeping up with https://github.com/ApollosProject/apollos-prototype/releases ?

This will require a little more diligence when a release is created - essentially going back through the commits included in the release and copy/pasting the commit title and the PR #.

Requires a little more time at the end, but we don't need to worry about it per PR, and then our releases page can link to the PRs/Commits for each "change" in that release, which is arguably a better changelog. Thoughts?

**Comment by IsaacHardy** [comment]
I really like using that package. Is the tag it generates customizable?

**Comment by conrad-vanl** [comment]
@IsaacHardy good question! We'll have to try it out :)

**Comment by conrad-vanl** [comment]
Looks like we have to follow these commit conventions: https://github.com/bcoe/conventional-changelog-standard/blob/master/convention.md

🤔

**Comment by conrad-vanl** [comment]
Here's the actual commit spec website: https://conventionalcommits.org/

I'm not against the idea of adhering to this....but wondering if we have to

**Comment by IsaacHardy** [comment]
To run the script, you will `cd` into the `scripts` directory on root, and run 

`sh release.sh <version_num>`

Where `version_num` equals your next incremented version number. (e.g. 0.4.0).

The script will update both iOS and Android application binary with the correct version, and also update both API and MOBILE directories `package.json` version number.

Finally, the script updates the change log based on specific commit messages found in the git log.

**Comment by IsaacHardy** [comment]
@vinnyjth @richarddubay @burkeshartsis @cdanwards Would like some input from y'all.

I'm updating this PR to contain a new change-log script and release script. The release script merely updates the Android and iOS versions while the change-log will grab our squashed merge commits and generate/update a change-log.

@conrad-vanl and I are wanting feedback on how we think we could organize these messages in a clear and meaningful way.

**Comment by conrad-vanl** [comment]
For more clarity to the above ^, right now what we 've talked about doing is we'll just take the commit messages generated by each PR. Right now, they'd look like this:

```

- 161 Adding individual devos to the home feed (#195) (ef3ba9b)
- 136 Discover Feed (#197) (a7b73db)
- [API] Enable Absolute Local Imports (#194) (fdf08f3)
- Improved splashscreen dismissal (8adfb52)
```

We want to get better at writing these messages. How do we communicate that in our PR template?

**Comment by IsaacHardy** [comment]
@vinnyjth @burkeshartsis @richarddubay @cdanwards Just wanted to tag you all again for feedback.

**Comment by vinnyjth** [comment]
@IsaacHardy I like this approach! This gives me more incentive to have more descriptive names for my PRs.

**Comment by IsaacHardy** [comment]
@vinnyjth and @burkeshartsis Specifically, we are "wanting feedback on how you think we could organize these messages in a clear and meaningful way."

**Comment by cdanwards** [comment]
I think that if we made it so that each PR title is a high level overview of what is going on in the PR it would help a lot. PR's like #155 , #159 , or #150 are clear on what's going on in the PR. One's like #135 or #174 are less clear.

**Comment by IsaacHardy** [comment]
@cdanwards That is actually the topic of discussion. How should we structure those PR titles?

**Comment by conrad-vanl** [comment]
I'll go. My vote would be to structure PR titles similar to user stories, specifying what the result of that PR does. 

> User can see their name and profile picture on the connect screen once logged in

Is a 💯 A++ 👍  PR title.

Something like:

> 182 - Design GraphQL schema for ESV scripture

I would write to be something more like:

> Ability to query for ESV scripture in GraphQL

**Comment by richarddubay** [comment]
Okay, my turn. I don't think this needs to be terribly convention heavy. I think these need to be simple one sentence structures. Start with words that say what you did. Things like `Updated`, `Added`, `Removed`, `Changed`. Then add what you changed.

> Added individual devotionals to the home feed.

I think that is as hard as this needs to be.

I did notice that some PR's tend to wrap more than one `feature` or major change in them. Is it feasible to think that we could break up big changes into multiple PR's in order to get more specific about what is changing? Perhaps we break them up into features? For example, #197 actually has to important things in it. It (1) changed the sorting order of individual feeds to be in newest first order, and it (2) added topics to the discover feed. But using that as a PR title is kind of long. That PR should probably have been two PR's. 

So instead of:
> #136 Discover Feed

or even:
> Changed the sorting order of individual feeds to be in newest first order and added News and Stories topics to the discover feed.

Maybe this becomes two PR's:

- > Changed the sorting order of individual feeds to be in newest first order.
- > Added News and Stories topics to the Discover feed.

I guess maybe that just means that we need to make sure that our issues are broken down into individual features and do not encompass more than one major change? FWIW, I think I added the sorting order change to the PR mentioned above because I noticed it was not the correct order and just thought I'd fix it while I was already in that code. So that one is one me ... maybe this isn't really an issue?

**Comment by conrad-vanl** [comment]
@richarddubay for your #136 Discover Feed example, I think it could also just be:

> Improved content feeds by adding new sections and adjusting order of items

If we need more details (like specifying _what_ the new sections are, or what the _new_ order is) we can do that in the commit body (when we merge the PR we can tweak the PR commit message body as well)

**Comment by IsaacHardy** [comment]
@conrad-vanl updated PR template

**Pull request merged**
