### PR TITLE
Fixes wrong campus being selected under certain conditions

### LINKED ISSUE #946: Wrong campus being selected under certain conditions
### Details

When the select campus screen loads, under certain conditions, the default campus may be a campus other than Cincinnati. If you select that campus, without changing Campuses, the selected Campus will be Cincinnati. 

ezgif-2-09d953219b87

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

### PR DESCRIPTION
**Pull request by vinnyjth**
### What does this PR do, or why is it needed?
Fixes issue where the wrong campus would be a selected, if a user's location was received and new data was fetched after the map rendered, and the user never interacted with the campus selector. 

This was due to `this.state.campuses` never been updated with the new "index 0" campus. Removing campus from state and calculating the current campus on the fly fixes this issue. 

### What design trade-offs/decisions were made?

n/a

### How do I test this PR?

1. Open the location finder from a geolocation close to either Dallas or North Carolina 
2. Watch as the first campus card (cincinnati) changes to either Dallas or Anderson
3. Click the select campus button
  - your sellected campus should be either dallas or anderson (whatever you are closest to)

### What automated tests did you write?
n/a

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes #946 
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
Note: the gif looks really weird because I used `setTimeout` + a fake navigator to set my current location. Shouldn't impact "in real life" functionality.

**Comment by redreceipt** [comment]
I'm confused, what is the intended behavior? and what was it doing before?

**Comment by vinnyjth** [comment]
@redreceipt Before, it would seem like you were selecting dallas, but it would actually select Cincinnati. Take a look at the gif in the attached issue.

**Comment by redreceipt** [comment]
ah

**Pull request merged**
