### PR TITLE
Remove required flag from certain schema attributes 

### PR DESCRIPTION
**Pull request by vinnyjth**
## DESCRIPTION

I have found that having attributes marked as required can be brittle, for example, parts of our app now throw errors if you don't put in a first name on onboarding. Technically a first name is not great, but GraphQL shouldn't be throwing errors just trying to query for it.

### What does this PR do, or why is it needed?

Removes the required marker from `attributes` on types in the schema that have the marker. 

### What design trade-offs/decisions were made?

Schema no longer reflects "base case scenario" for data cleanliness as closely. 

### How do I test this PR?

1. Boot the app, it shouldn't fail.
2. Create a new user and opt to avoid setting a first name. The app will no longer throw an error.

### What automated tests did you write?

n/a

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
`apollos-church-api/local.graphql` has been updated, I'll go ahead and push the changes, just FYI

**Comment by redreceipt** [comment]
Not sure if this is the intended behavior or not, the Next button doesn't show up so you have to swipe. If it is, then it works like a charm :)

Kapture 2019-06-23 at 14 14 43

**Comment by vinnyjth** [comment]
Thanks for pointing that out @redreceipt. On the UI side, that field is still required. However, marking it as required in the schema means that GQL won't even try to resolve queries where that field is `null`, which is bad news for us.

**Comment by redreceipt** [comment]
So maybe a separate issue but should we disable the swipe until validation issues are resolved?

**Comment by vinnyjth** [comment]
That's a good question for @burkeshartsis

**Comment by vinnyjth** [comment]
> Would this be considered a breaking schema change? 

It is according to the schema tool, but because clients don't care about if a field is required or not when querying (they don't specify the `!` it's not. The only situation I've found so far when you can't remove a required field, is when using input types. `input { foo: String! }` -> `input { foo: String }` is breaking, because you normally specify inputs like so `query($foo: String!) { thing(foo: $foo) } `

**Pull request merged**
