### PR TITLE
Fixes close button navigating back too far

### PR DESCRIPTION
**Pull request by vinnyjth**
## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
I think this fix was in #698, but I was wrong! @IsaacHardy or @richarddubay Would you mind taking a look to see if this fixes the issue you had where going back from a content item would take you to a prayer or something? You can apply the same changes to your codebase.

**Comment by IsaacHardy** [comment]
@vinnyjth This fix did work halfway. Currently, this is still an issue the FIRST time some presses the X. However, after that initial issue, it never happens again.

**Comment by cdanwards** [comment]
@vinnyjth I actually independently came to the same changes to fix the issue and after testing in our repo, it's working there too!

**Comment by vinnyjth** [comment]
@cdanwards In that case, can you review + merge this :D

**Pull request merged**
