### PR TITLE
Makes Android Development Smoother

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

kapture 2019-03-07 at 15 45 22

### What does this PR do, or why is it needed?

Currently developing with Android is a pain in `react-native`. This just makes our lives a little easier by making `yarn android` a one-stop shop. It adds two features:

- Automatically opens the first emulator you have installed in Android Studio
- Automatically opens the app when the build is done

### What design trade-offs/decisions were made?

The only thing I don't like is it leaves the terminal tab open while the emulator is open. But that is native Android `emulator` functionality. And it's still better than having to open Android Studio. Ideally, we could push it to the background.

### How do I test this PR?

`yarn start` then `yarn android`

### What automated tests did you write?

n/a

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@redreceipt This is really slick. You could probably get rid of the requirement to have the terminal tab open by appending the command with `&`

**Comment by vinnyjth** [comment]
I tried to review this locally, but ran into issues with how my CLI is setup and Android Studio, so was not able to get it working. Would gladly approve this given I trust that it works if your setup is workign correctly, but would also love to get @burkeshartsis's eyes on it.

**Comment by redreceipt** [comment]
@vinnyjth what is the error that you're getting? the goal is that it would just "work" for everyone so maybe there's a way to get yours and everyone's environment set up the same as part of this PR too.

and I did use the `&` with the emulator command which I think is the one hanging it up, but I didn't want to push the build process to the background in case there is a legitimate build error.

**Comment by vinnyjth** [comment]
image

There are two errors in the log, one about not being able to find the device, and one about not being able to determine Java version.

**Comment by redreceipt** [comment]
what's the output of `java -version` for you?

**Comment by vinnyjth** [comment]
@redreceipt It was OpenJDK 11. I fixed all the issues by doing the following. 

1. Setting `ANDROID_HOME`
2. Installing Java 8
3. Setting `JAVA_HOME` to Java 8

**Comment by redreceipt** [comment]
@vinnyjth I'm thinking the minimum may be to just set `ANDROID_HOME` which we can do in the command itself. I don't have a separate instance of Java installed, should be included in Android dev tools I think. My `JAVA_HOME` is blank.

I'll be interested to see what happens for others, would love a couple more reviews before it's merged to cover all the bases.

**Comment by conrad-vanl** [comment]
I'll take the final review on this - i have two different android environments set up.

**Comment by conrad-vanl** [comment]
SOOOO I just get:

```
/bin/sh: emulator: command not found
```

😇

**Comment by redreceipt** [comment]
@conrad-vanl ok not surprised. So try changing `emulator` to `$HOME/Library/Android/sdk/emulator` and see what happens. It comes with Android SDK so it's on your computer in one of two locations. If it's the other, I'll just have to get a little creative.

I'm trying to make to where you don't have to touch your `.bashrc`

**Comment by redreceipt** [comment]
@conrad-vanl I made the change, try it now

**Pull request merged**
