### PR TITLE
Upgrade React Native

### PR DESCRIPTION
**Pull request by redreceipt**
## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
error on `yarn start`:
```
apolloschurchapp: (node:49328) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
apolloschurchapp:   Duplicate module name: react-native
apolloschurchapp:   Paths: /Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apolloschurchapp/node_modules/@storybook/react-native/node_modules/react-native/package.json collides with /Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apolloschurchapp/node_modules/react-native/package.json
apolloschurchapp: This error is caused by `hasteImpl` returning the same name for different files.
apolloschurchapp:     at setModule (/Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apolloschurchapp/node_modules/jest-haste-map/build/index.js:569:17)
apolloschurchapp:     at workerReply (/Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apolloschurchapp/node_modules/jest-haste-map/build/index.js:641:9)
apolloschurchapp:     at processTicksAndRejections (internal/process/next_tick.js:81:5)
apolloschurchapp: (node:49328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
apolloschurchapp: (node:49328) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
apolloschurchapp: (node:49328) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
apolloschurchapp:   Duplicate module name: react-native
apolloschurchapp:   Paths: /Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apolloschurchapp/node_modules/@storybook/react-native/node_modules/react-native/package.json collides with /Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apolloschurchapp/node_modules/react-native/package.json
apolloschurchapp: This error is caused by `hasteImpl` returning the same name for different files.
apolloschurchapp:     at setModule (/Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apolloschurchapp/node_modules/jest-haste-map/build/index.js:569:17)
apolloschurchapp:     at workerReply (/Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apolloschurchapp/node_modules/jest-haste-map/build/index.js:641:9)
apolloschurchapp:     at processTicksAndRejections (internal/process/next_tick.js:81:5)
apolloschurchapp: (node:49328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by redreceipt** [comment]
woohoo! ok I'll keep chugging along

**Comment by redreceipt** [comment]
@conrad-vanl getting an error after merge

```
error An unexpected error occurred: "could not find a copy of react-native to link in /Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@apollosproject/ui-htmlview/node_modules"
```

**Comment by redreceipt** [comment]
...stay tuned. think I've got a solution.

**Comment by redreceipt** [comment]
@conrad-vanl getting this error now trying to `yarn`:

```
lerna ERR! yarn run build stderr:
{ Error: [BABEL] /Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apollos-church-api/src/config.js: Cannot find module '@babel/plugin-proposal-export-default-from' from '/Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apollos-church-api'
    at Function.module.exports [as sync] (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/resolve/lib/sync.js:58:15)
    at resolveStandardizedName (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:40:19) code: 'MODULE_NOT_FOUND' }
error Command failed with exit code 1.
```

**Comment by conrad-vanl** [comment]
@vinnyjth any ideas on this? doesn't seem related to the r-n upgrade

**Comment by vinnyjth** [comment]
Looks like it might be a dep issue caused by an update to the `metro-react-native-babel-preset`

image

image

I'm not sure how to fix off the top of my head. @redreceipt, do you get that error during the `build` step of `yarn` or the `install` step?

**Comment by redreceipt** [comment]
@vinnyjth here's the full output of `yarn`:

```
~/Documents/Projects/apollos-prototype (upgrade) $ yarn
yarn install v1.13.0
[1/4] 🔍  Resolving packages...
warning Resolution field "babel-core@7.0.0-bridge.0" is incompatible with requested version "babel-core@^6.0.0"
warning Resolution field "babel-core@7.0.0-bridge.0" is incompatible with requested version "babel-core@^6.0.0"
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @apollosproject/ui-htmlview@0.8.0-alpha.8" has unmet peer dependency "@apollos-project/ui-kit@*".
warning " > @apollosproject/ui-passes@0.8.0-alpha.9" has unmet peer dependency "@apollos-project/ui-kit@*".
warning " > @apollosproject/ui-passes@0.8.0-alpha.9" has unmet peer dependency "react-native-passkit-wallet@*".
warning " > @apollosproject/ui-passes@0.8.0-alpha.9" has unmet peer dependency "rn-fetch-blob@*".
warning "workspace-aggregator-c1ac29a1-634c-4389-abe5-b54ca7d9cabc > @apollosproject/ui-htmlview > @storybook/react-native@4.1.13" has unmet peer dependency "babel-runtime@>=6.0.0".
warning "workspace-aggregator-c1ac29a1-634c-4389-abe5-b54ca7d9cabc > @apollosproject/ui-passes > react-apollo@2.5.2" has unmet peer dependency "apollo-client@^2.5.1".
warning "workspace-aggregator-c1ac29a1-634c-4389-abe5-b54ca7d9cabc > @apollosproject/ui-passes > react-apollo@2.5.2" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-c1ac29a1-634c-4389-abe5-b54ca7d9cabc > apolloschurchapp > react-native-video-controls@2.2.3" has incorrect peer dependency "react-native-video@^2.0.0".
warning "workspace-aggregator-c1ac29a1-634c-4389-abe5-b54ca7d9cabc > apolloschurchapp > @storybook/react-native@4.0.7" has unmet peer dependency "babel-runtime@>=6.0.0".
warning "workspace-aggregator-c1ac29a1-634c-4389-abe5-b54ca7d9cabc > @apollosproject/data-connector-bible > apollo-datasource-rest > apollo-server-errors@2.2.0" has unmet peer dependency "graphql@^0.12.0 || ^0.13.0 || ^14.0.0".
[4/4] 🔨  Building fresh packages...
$ lerna run build --parallel
lerna notice cli v3.13.1
lerna info Executing command in 14 packages: "yarn run build"
@apollosproject/apollo-server-env-mock: yarn run v1.13.0
apollos-church-api: yarn run v1.13.0
@apollosproject/config: yarn run v1.13.0
@apollosproject/data-connector-analytics: yarn run v1.13.0
@apollosproject/data-connector-analytics: warning package.json: No license field
@apollosproject/data-connector-church-online: yarn run v1.13.0
@apollosproject/data-connector-bible: yarn run v1.13.0
@apollosproject/data-connector-cloudinary: yarn run v1.13.0
@apollosproject/data-connector-twilio: yarn run v1.13.0
@apollosproject/data-connector-rock: yarn run v1.13.0
@apollosproject/data-connector-onesignal: yarn run v1.13.0
@apollosproject/data-connector-church-online: warning package.json: No license field
@apollosproject/data-connector-bible: warning package.json: No license field
@apollosproject/data-schema: yarn run v1.13.0
@apollosproject/data-connector-passes: yarn run v1.13.0
@apollosproject/data-connector-cloudinary: warning package.json: No license field
@apollosproject/data-connector-twilio: warning package.json: No license field
@apollosproject/data-connector-onesignal: warning package.json: No license field
@apollosproject/rock-apollo-data-source: yarn run v1.13.0
@apollosproject/server-core: yarn run v1.13.0
@apollosproject/data-connector-rock: warning package.json: No license field
@apollosproject/apollo-server-env-mock: $ NODE_ENV=production rm -rf ./lib && mkdir -p lib && babel ./src -d ./lib
apollos-church-api: $ NODE_ENV=production rm -rf ./lib && mkdir -p lib && babel ./src -d ./lib
@apollosproject/data-connector-passes: warning package.json: No license field
@apollosproject/config: $ NODE_ENV=production rm -rf ./lib && mkdir -p lib && babel ./src -d ./lib
@apollosproject/data-connector-analytics: $ NODE_ENV=production rm -rf ./lib && mkdir -p lib && babel ./src -d ./lib
@apollosproject/data-connector-bible: $ NODE_ENV=production rm -rf ./lib && mkdir -p lib && babel ./src -d ./lib
@apollosproject/data-connector-church-online: $ NODE_ENV=production rm -rf ./lib && mkdir -p lib && babel ./src -d ./lib
@apollosproject/data-connector-cloudinary: $ NODE_ENV=production rm -rf ./lib && mkdir -p lib && babel ./src -d ./lib
@apollosproject/data-schema: $ NODE_ENV=production rm -rf ./lib && mkdir -p lib && babel ./src -d ./lib
@apollosproject/data-connector-twilio: $ NODE_ENV=production rm -rf ./lib && mkdir -p lib && babel ./src -d ./lib
@apollosproject/data-connector-onesignal: $ NODE_ENV=production rm -rf ./lib && mkdir -p lib && babel ./src -d ./lib
@apollosproject/rock-apollo-data-source: $ NODE_ENV=production rm -rf ./lib && mkdir -p lib && babel ./src -d ./lib
@apollosproject/data-connector-rock: $ NODE_ENV=production rm -rf ./lib && mkdir -p lib && babel ./src -d ./lib
@apollosproject/data-connector-passes: $ NODE_ENV=production rm -rf ./lib && mkdir -p lib && babel ./src -d ./lib
@apollosproject/server-core: $ NODE_ENV=production rm -rf ./lib && mkdir -p lib && babel ./src -d ./lib
@apollosproject/apollo-server-env-mock: { Error: [BABEL] /Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apollos-apollo-server-env-mock/src/apollo-datasource-mocks/bible.js: Cannot find module '@babel/plugin-proposal-export-default-from' from '/Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apollos-apollo-server-env-mock'
@apollosproject/apollo-server-env-mock:     at Function.module.exports [as sync] (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/resolve/lib/sync.js:58:15)
@apollosproject/apollo-server-env-mock:     at resolveStandardizedName (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
@apollosproject/apollo-server-env-mock:     at resolvePlugin (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
@apollosproject/apollo-server-env-mock:     at loadPlugin (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
@apollosproject/apollo-server-env-mock:     at createDescriptor (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
@apollosproject/apollo-server-env-mock:     at items.map (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
@apollosproject/apollo-server-env-mock:     at Array.map (<anonymous>)
@apollosproject/apollo-server-env-mock:     at createDescriptors (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
@apollosproject/apollo-server-env-mock:     at createPluginDescriptors (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
@apollosproject/apollo-server-env-mock:     at plugins (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:40:19) code: 'MODULE_NOT_FOUND' }
apollos-church-api: { Error: [BABEL] /Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apollos-church-api/src/config.js: Cannot find module '@babel/plugin-proposal-export-default-from' from '/Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apollos-church-api'
apollos-church-api:     at Function.module.exports [as sync] (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/resolve/lib/sync.js:58:15)
apollos-church-api:     at resolveStandardizedName (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
apollos-church-api:     at resolvePlugin (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
apollos-church-api:     at loadPlugin (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
apollos-church-api:     at createDescriptor (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
apollos-church-api:     at items.map (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
apollos-church-api:     at Array.map (<anonymous>)
apollos-church-api:     at createDescriptors (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
apollos-church-api:     at createPluginDescriptors (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
apollos-church-api:     at plugins (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:40:19) code: 'MODULE_NOT_FOUND' }
apollos-church-api: error Command failed with exit code 1.
apollos-church-api: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@apollosproject/data-connector-analytics: { Error: [BABEL] /Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apollos-data-connector-analytics/src/__tests__/data-source.tests.js: Cannot find module '@babel/plugin-proposal-export-default-from' from '/Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apollos-data-connector-analytics'
@apollosproject/data-connector-analytics:     at Function.module.exports [as sync] (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/resolve/lib/sync.js:58:15)
@apollosproject/data-connector-analytics:     at resolveStandardizedName (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
@apollosproject/data-connector-analytics:     at resolvePlugin (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
@apollosproject/data-connector-analytics:     at loadPlugin (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
@apollosproject/data-connector-analytics:     at createDescriptor (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
@apollosproject/data-connector-analytics:     at items.map (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
@apollosproject/data-connector-analytics:     at Array.map (<anonymous>)
@apollosproject/data-connector-analytics:     at createDescriptors (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
@apollosproject/data-connector-analytics:     at createPluginDescriptors (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
@apollosproject/data-connector-analytics:     at plugins (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:40:19) code: 'MODULE_NOT_FOUND' }
lerna ERR! yarn run build exited 1 in 'apollos-church-api'
lerna ERR! yarn run build stdout:
yarn run v1.13.0
$ NODE_ENV=production rm -rf ./lib && mkdir -p lib && babel ./src -d ./lib
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
{ Error: [BABEL] /Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apollos-church-api/src/config.js: Cannot find module '@babel/plugin-proposal-export-default-from' from '/Users/michael.neeley/Documents/Projects/apollos-prototype/packages/apollos-church-api'
    at Function.module.exports [as sync] (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/resolve/lib/sync.js:58:15)
    at resolveStandardizedName (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/Users/michael.neeley/Documents/Projects/apollos-prototype/node_modules/@babel/core/lib/config/config-descriptors.js:40:19) code: 'MODULE_NOT_FOUND' }
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'apollos-church-api'
lerna WARN complete Waiting for 13 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by conrad-vanl** [comment]
@vinnyjth I've looked at this a few times now, and I'm at a complete loss at whats going on here. All of the API packages are dying with the same error -

```
Cannot find module '@babel/plugin-proposal-export-default-from' from '/Users/conrad/Sites/apollos-prototype/packages/apollos-church-api'
```

**Comment by vinnyjth** [comment]
@conrad-vanl Sure thing, I'll see what I can find.

**Comment by redreceipt** [comment]
@vinnyjth we should prob QA this on actual devices wouldn't you say? I can get started on that whenever you're done with changes

**Comment by vinnyjth** [comment]
@redreceipt Feel free, I'm done making changes.

**Pull request merged**
