### PR TITLE
Adds Video Format to Schema

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

Adds a `format` arg to the `videos` field of a `ContentItem`

### What design trade-offs/decisions were made?

None.

### How do I test this PR?

Open the playground and make sure the schema shows up right.

### What automated tests did you write?

None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@redreceipt Can you tell me more about why you need this PR? How do you propose we send over the video format? Is it already on the video attribute?

**Comment by redreceipt** [comment]
It won't be implemented, just the schema. We'll resolve it on our end. Not really sure how we could write a default solution given different sources. I suppose we could just have two different fields in apollosrock and resolve it like that but it would almost certainly be overwritten by every partner. 

It's needed because Android can't do HLS yet.

**Comment by vinnyjth** [comment]
@redreceipt Given the context, I think this PR is okay. I'm struggling with the values of the `enum`. `mp4` is an encoding, while `hls` is more like a container. 

Regarding your android issues - have you tried enabling `exoplayer` instead of the default media player?

https://github.com/react-native-community/react-native-video/issues/1746

**Comment by vinnyjth** [comment]
@conrad-vanl I don't plan on merging this unless @redreceipt lets me know that Exoplayer didn't work for their team, on hold until then :)

**Comment by redreceipt** [comment]
it works you can close it

**Pull request closed without merging**
