### PR TITLE
Updates React Navigation to v3

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

Updates `react-navigation` to 3.0, hopefully will speed up the app and will solve some deep stack slow down issues.

### How do I test this PR?

Q/A on different nav paths.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [#407]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
https://reactnavigation.org/blog/2018/11/17/react-navigation-3.0.html

I've done the following:
1. updated `react-navigation` package
2. installed `react-native-gesture-handler` (https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#installation)
3. Wrapped main nav in new app container (https://reactnavigation.org/blog/2018/11/17/react-navigation-3.0.html#explicit-app-container-required-for-the-root-navigator)

Currently hung on start up.

Screen Shot 2019-06-25 at 10 03 00 AM

Not sure where to go from here. `react-native-gesture-handler` [mentions](https://reactnavigation.org/blog/2018/11/17/react-navigation-3.0.html#explicit-app-container-required-for-the-root-navigator) registering *every* screen in their HOC but that's with `react-native-navigation` so I'm not sure if it's necessary for our use case.

**Comment by vinnyjth** [comment]
@redreceipt any errors in your packager? I will give this a shot when I have a chance, this is a top priority for me.

**Comment by redreceipt** [comment]
> @redreceipt any errors in your packager? I will give this a shot when I have a chance, this is a top priority for me.

No packager errors

**Comment by vinnyjth** [comment]
@redreceipt I got the app booting again. Feel free to give this PR a test run and see how it works! I've got some issues with the tests that I need to fix though.

**Comment by redreceipt** [comment]
this one is ready, maybe @conrad-vanl give it look since we both touched it.

**Comment by redreceipt** [comment]
Currently stuck trying to fix tests with errors like this:

Screen Shot 2019-07-14 at 4 19 29 PM

**Pull request merged**
