### PR TITLE
Optionally Shows Error Cards

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

errors

### What does this PR do, or why is it needed?

Toggles `ErrorCard` based on an environment variable, defaults to hidden

### What design trade-offs/decisions were made?

Blank screen might be a little confusing but it's better than showing "GraphQL Error" all over the place.

### How do I test this PR?

Open the app without the server running.

### What automated tests did you write?

None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@redreceipt I talked with @burkeshartsis about this PR at length. I believe that this is the right "first step" but @burkeshartsis believes we might need more nuance about when and where we displays errors. 

We'll probably talk about if this PR should be merged today during our internal sync up meeting, I'll post updates here as I have them.

**Comment by redreceipt** [comment]
Cool.

My 2 cents, I think a better solution would just be a prettier `ErrorCard`, it just shouldn’t say anything techy

—
Michael

**Comment by richarddubay** [comment]
My opinion: I agree that it should probably just be a prettier error card. 

A white screen feels just as broken (if not more so) than a screen with an error that means nothing to people. 

Even something as "simple" as a church logo and "Oh no! We're sorry! We logged your error and notified Burke directly. Please try again." seems like it would be helpful.

FWIW, I feel like this is probably a something we'd want to handle before we launch.

**Comment by conrad-vanl** [comment]
Yeah, I'd vote to close this in favor of a prettier error card.

**Comment by redreceipt** [comment]
ok so @kevin-birdy wanna mock something up?

also @conrad-vanl currently it will simply layer the same pretty error card on top of each other in certain cases. are you ok with that behavior for round one until we can make it smarter?

**Comment by kevin-birdy** [comment]
Do we want any dynamic text at all or simply set it up as a catch all message?

This is a pretty straightforward take that gets the job done I think. If it makes things easier at all, the layout is action the same as `ActionCard` without the button and using `darkTertiary` instead as the header + `warning` icon.

ErrorCard

**Comment by redreceipt** [comment]
as soon as @conrad-vanl gives this a thumbs up I'll get started on it

**Comment by conrad-vanl** [comment]
ship it

**Comment by redreceipt** [comment]
closing, going in a different direction

**Comment by redreceipt** [comment]
#1239

**Pull request closed without merging**
