### PR TITLE
Adds <StretchyView /> component

### PR DESCRIPTION
**Pull request by conrad-vanl**
### What does this PR do, or why is it needed?

Adds a `<StretchyView />` component so that we can do stretchy headers!

### What design trade-offs/decisions were made?

NONE!

### How do I test this PR?

There are two stories added.

### What automated tests did you write?

Snapshots for both of the typical use cases.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by burkeshartsis** [comment]
🙃

Screen Shot 2019-07-23 at 12 51 06 PM

**Comment by burkeshartsis** [comment]
How was this tested for performance? Specifically did we test this on any lower end Android devices. There is some really clever code in here that I believe should allow this to work without major perf problem but we wont know unless we test.

**Comment by redreceipt** [comment]
> How was this tested for performance? Specifically did we test this on any lower end Android devices. There is some really clever code in here that I believe should allow this to work without major perf problem but we wont know unless we test.

good call, it didn't scroll for me on the pixel 2

**Comment by conrad-vanl** [comment]
It will stretch android just doesn’t have over scroll. So you have to make the content in the scroll view longer then the screen so you can see the affect.

I did light android testing on willow and didn’t notice performance implications. But let me know what you’d like me to do here...

Thanks!
---
Conrad VanLandingham

**Comment by redreceipt** [comment]
> It will stretch android just doesn’t have over scroll. So you have to make the content in the scroll view longer then the screen so you can see the affect. I did light android testing on willow and didn’t notice performance implications. But let me know what you’d like me to do here... Thanks! --- Conrad VanLandingham
> […](#)
> On Jul 23, 2019, 12:51 PM -0500, Michael Neeley ***@***.***>, wrote: @redreceipt requested changes on this pull request. pixel 2 doesn't stretch — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

oh well in that case I'm good

**Comment by conrad-vanl** [comment]
@burkeshartsis are you still trying to review this or is it good to merge?

**Comment by conrad-vanl** [comment]
So I did a thing, made this component vastly more complex but I think the API it exposes is just as simple, if not simpler, while allowing for more features (stretchy headers and footers). It also MIGHT be more performant because the Stretchy now gets rendered inside of the ScrollView:

https://slack-files.com/T0251KCHT-FLREFFWTE-45b86b9307

**Comment by conrad-vanl** [comment]
So essentially the API now looks like this:

```
<StretchyView>
   {({ Stretchy, ...scrollViewProps }) => (
      <ScrollView {...scrollViewProps}>
         <Stretchy>
             <Image {...} />
         </Stretchy>
         {...other scroll content...}
      </ScrollView>
   )}
</StretchyView>
```

`StretchyView` takes in a function as `children`, and passes in a `Stretchy` component and `scrollViewProps` as its argument. You then can render the `Stretchy` component whereever you want inside of your `ScrollView`, and `StretchyView` is smart in figuring out how to display it.

By default a `Stretchy` will "stick" to the top of the screen when over-scrolling. To make a `Stretchy` a footer, you pass `stretchOn="bottom"` as a prop:

```
<Stretchy stretchOn="bottom" />
```

You can also have multiple stretchies, you just have to supply a unique key to each Stretchy:

```
<Stretchy stretchyKey="myFirstStretchy" stretchOn="top" />
<Stretchy stretchyKey="mySecondStretchy" stretchOn="bottom" />
```

The content you put inside of `Stretchy` actually gets rendered twice: once inside of the `ScrollView`, and once outside of the `ScrollView`. During overscrolling, the `Stretchy` inside of the `ScrollView` becomes hidden, and the `Stretchy` outside of the scrollview appears and animates.

I am pondering an alternative API that might simplify code a bit, and is a bit more imperative, but might be a little more awkward to use:

```
<StretchyView
   StretchyHeader={<MyStretchyHeaderContent />}
   StretchyFooter={<MyStretchyFooterContent />}
>
  {({ StretchyHeader, StretchyFooter }, scrollViewProps) => (
    <ScrollView {...scrollViewProps}>
      <StretchyHeader />
      {...other scrollview content...}
      <StretchyFooter />
    </ScrollView>
  )}
</StretchyView>
```

Essentially, you'd imperatively define your `StretchyHeader` and `StretchyFooter` as props in `StretchyView`. Then, the children render function would get both a `StretchyHeader` and `StretchyFooter` argument that you still need to render inside of your `ScrollView`. This would simplify some code inside of the component, and remove the `stretchOn` and `stretchyKey` props in the previous example.

The negative is it limits you to just one stretchy header and one stretchy footer, which the current code base would support any arbitrary number of Stretchies. I don't know if that's a good thing though.

@vinnyjth if you have time, would love your thoughts on this as well. Ultimately, I think we should just decide on the right API then get this merged.

**Pull request merged**
