### PR TITLE
Check for Valid Images When Rendering Campus Cards.

### PR DESCRIPTION
**Pull request by erikkgagewhitt**
### What does this PR do, or why is it needed?

Adds a check to the CampusCard component that ensures that all images passed to it are indeed valid.

This means it checks that the array exists, that none of the objects in the array are equal to `null`, and that the `uri` key in the objects is not null.

The change is intended to fix an issue that occurs in the New Spring app, but the protection should be added to core, thus this PR!

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by erikkgagewhitt** [comment]
@conrad-vanl It looks like there's more than just this crash. Some of NewSpring's components (like Marker) require values from a campus.

The campus in question ("Web") has all of its values set to null and so crashes any component that uses it.

**Comment by conrad-vanl** [comment]
Nice @erikkgagewhitt .

@richarddubay what do you think? I know you said the web campus shouldn't show in the list but it looks like that's the issue. Any idea what changed on y'alls end?

We're happy to look at merging this if you want.

**Comment by richarddubay** [comment]
It's weird that "Web" is showing up for you, but I guess that would make sense that it would crash if it does. There is nothing at all set up in Rock for that campus.

Can you show me where you're seeing "Web" show up? I ran the `getAllCampuses` query and it only returns the 14 active and public campuses.

**Comment by richarddubay** [comment]
So I did a little more research. It turns out that I could get the app to freeze on the settings screen after tapping "Location" by changing my campus to "Web". The `getAllCampuses` query then returns the Web campus with an image of "null" for `currentUser`. It seems to make sense that this change would then stop the app from freezing, but I can't think of a really good way to test it.

**Comment by erikkgagewhitt** [comment]
Interesting; when I signed up for the app, I skipped the campus step. Does that cause the user's campus to be set as "Web"?

**Comment by richarddubay** [comment]
@erikkgagewhitt Yep! It's our catch against a person not having any campus set at all.

**Comment by conrad-vanl** [comment]
Woah @vinnyjth I thought `mergify` wouldn't merge if there were any failing checks?

**Comment by redreceipt** [comment]
> Woah @vinnyjth I thought `mergify` wouldn't merge if there were any failing checks?

It adheres to our github rules. you can merge with codecov fails but not travis test fails.

**Comment by conrad-vanl** [comment]
ah ok

**Pull request merged**
