### PR TITLE
Cleans up and fixes lots of UI/UX related Onboarding issues

### LINKED ISSUE #649: Onboarding Screen Loading Animation on button interactions
### User Story

As a `user` I want to `have clear indicators on what is happening after I interact with a"Next" button on the onboarding screen` so that I can `be confident that I did the correct interaction on the screen`.

### Description
This feature ads a loading animation to the center of the empty gray button that shows up after pressing "Next" on the Onboarding screens

### Why
After pressing "Next", the empty gray button doesn't give a clear picture of what's going on and can appear as though something isn't working correctly. Adding a familiar loading spinner to the component clearly communicates to the user that the app is waiting on something.

### Acceptance Criteria
* [ ] It should show an animated loading spinner after the "Next" button is pressed 

### Possible Implementation & Open Questions
A standard loading spinner inside the UI Kit would be awesome
It would also be great to have the ability to override the default with a custom component that renders wherever the default component is used

### Other Resources
*https://pin.it/einh4zmca5cxhr
*https://pin.it/m75gulkolpzreu
*https://pin.it/unb3j6rmobyw2j
*https://pin.it/44lsrviwcqm4xh

### PR DESCRIPTION
**Pull request by conrad-vanl**
### What does this PR do, or why is it needed?

1. Adds `SafeAreaView` to onboarding slides
2. Create consistency among the onboarding slides

### What design trade-offs/decisions were made?

There's a really nasty hack to achieve number 1 above...this is due to a layout bug in the swiper component, as far as I can tell and its compatibility with `SafeAreaView`

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes #649 #651 #652 
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@burkeshartsis i think we can run the demo from this branch

**Comment by conrad-vanl** [comment]
Or, we can get this branch merged and a new release on testflight, and demo that!

**Comment by vinnyjth** [comment]
@burkeshartsis Soon as we get this reviewed, I can start putting Onboarding into its own package. Let me know if you need help :)

**Comment by conrad-vanl** [comment]
@burkeshartsis messed with the safe area view stuff for a bit. I think this is in a decent spot, but still see a few issues:

1. the verification/pin screen on sms login the next button is messed up and no loading state
2. the next button on the name entry state doesn't have a loading state when submitting the form
3. the next button on the gender screen doesn't have a loading state when submitting the form
4. The title on the "Hey friend" screen isn't padded correctly at the top. I think my changes introduced this, but for the life of me I can't figure out why it isn't when the other slides are

I can work on this some more today...

**Comment by conrad-vanl** [comment]
@vinnyjth @burkeshartsis this should be readyh...just for some reason the `AboutYou` tests are hanging now. Not sure why...

**Comment by burkeshartsis** [comment]
I'll take a look at them.

**Comment by conrad-vanl** [comment]
locally if I do something like `yarn run test -t "AboutYou"` the jest output is fine, then randomly I get:

```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.
```

and it just hangs

**Comment by burkeshartsis** [comment]
@conrad-vanl looks like tests are handing at `apollos-data-connector-rock`. Running tests from within the directory directly though seems to work fine. @vinnyjth any ideas?

**Comment by vinnyjth** [comment]
@burkeshartsis How can you tell tests are hanging at `apollos-data-connector-rock`? I'm seeing them hang at `AboutYou` as well.

**Comment by burkeshartsis** [comment]
@vinnyjth I was running tests from apollos root and that's where it stuck. Running tests from `apolloschurchapp` now hangs at `AboutYou` for me too. 

Could we be hitting the picsum api limit?

**Comment by vinnyjth** [comment]
Looks like something to do with the YellowBox warning.

**Comment by burkeshartsis** [comment]
yeah I'm looking into some of the warning now.

**Comment by burkeshartsis** [comment]
### Merge! Merge! Merge!

**Pull request merged**
