### PR TITLE
Updates description style for HorizontalDefaultCard

### PR DESCRIPTION
**Pull request by burkeshartsis**
### What does this PR do, or why is it needed?
This updates the `description` to use `BodySmall` for the `HorizontalDefaultCard`.

### What design trade-offs/decisions were made?
This change is an approximation of the desired design. To for this to be visually correct we would have to change the `BodySmall` which is currently 14px to 12px across the app.

### How do I test this PR?
stories

### What automated tests did you write?
🍪

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by kevin-birdy** [comment]
@burkeshartsis I'm sorry I think I might've confused myself talking with jordan and made a mistake here.

Was this previously using H6? `BodySmall` is definitely 14px... but I just combed the UI Kit and it looks like this is actually H6 and the real discrepancy that Jordan found was that H6 in Github is bold and H6 in Figma is regular.

This is the only place I can find `BodySmall` in its current state (`CampusCard`). So, if that's the case...I am probably not utilizing `BodySmall` as well as I should be.

Screen Shot 2019-12-11 at 9 10 30 AM

So...now we have a couple of options that I see:
1. Keep `H6` bold and make `BodySmall` 12px regular
2. Update `BodySmall` to 14px and change `H6` to regular

Given the above, I actually think you are heading down the right track and we go with option 1. The only thing that I can see that I need to update is `CampusCard` (which, isn't called that anymore? Help me find it in Storybook so I can see what we are currently using for the description?)

**Comment by kevin-birdy** [comment]
Basically every instance of `H6` is currently being used as a description text (hence why I had it as `regular`... so one thing to note is that if we did make `BodySmall` 12px regular it would essentially nullify `H6` other than the possibility of a little caption/disclaimer or something like that.

**Comment by burkeshartsis** [comment]
@kevin-birdy so for better or worse combing the app for `H6` usage reveals more references than I think you have in the "design kit." We can totally audit this later but I agree the safest, easiest, and most semantic route is to update `BodySmall`. This would leave `H6` to continue to be a "header" and let `BodySmall` be the caption/subtext/smaller bodied `BodyText` brother it was always meant to be.

**Comment by kevin-birdy** [comment]
Sounds like a plan to me

**Comment by burkeshartsis** [comment]
So for clarity, we are going to keep this PR as it stands. It updates the `HorizontalDefaultCard` to use `BodySmall` even though the styling on `BodySmall` isn't correct. This #1267 updates `BodySmall` to the correct size of 12px.

**Comment by kevin-birdy** [comment]
Yes! 100% on board.

**Pull request merged**
