### PR TITLE
Adds Highlight Card

### LINKED ISSUE #851: [UI] FeaturedCard and HighlightCard
### User Story

As a user I want to experience a "Live" sermon experience that combines sermon information with the livestream.

### Description
This is a `FeaturedCard` and `HighlightCard` to be displayed in the home feed. These cards are visually distinctive from other cards/content in the feed used to highlight their rich media content. 

image

### Acceptance Criteria
- [ ] It should gracefully handle it's props in a way that if one was missing it might still function.
- [ ] It should accept custom title, description, and label text.
- [ ] The label should accept a custom background color but default to brand or transparent coloring.
- [ ] It should accept a custom gradient color and default to brand coloring.
- [ ] It should display if it has been liked or not
- [ ] It should accept media icon and default to "play"

### Other Resources

- [Basecamp todo](https://3.basecamp.com/3926363/buckets/6947926/todos/1898958850)

### PR DESCRIPTION
**Pull request by vinnyjth**
### What does this PR do, or why is it needed?

Adds Highlight Card mentioned in #851 

### What design trade-offs/decisions were made?
n/a
### How do I test this PR?
Check storybook
### What automated tests did you write?
Snapshots
## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes #851
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [x] Manual QA on iOS and ensure it looks/behaves as expected
- [x] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [x] Read through the "Files changed" tab _very carefully_
- [x] Edge cases: what assumptions are made about input?
- [x] What kind of tests could be written?
- [x] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [x] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
image

**Comment by vinnyjth** [comment]
image

**Comment by vinnyjth** [comment]
image

**Comment by vinnyjth** [comment]
image

**Comment by conrad-vanl** [comment]
Blocked due to #867

**Comment by burkeshartsis** [comment]
@vinnyjth #867 should have everything this PR needs to copy over now.

**Comment by vinnyjth** [comment]
@burkeshartsis this is caught up to date.

**Comment by burkeshartsis** [comment]
Thanks! I might take a look at this later today or on Monday.

**Pull request merged**
