### PR TITLE
Notifications Soft Ask

### PR DESCRIPTION
**Pull request by erikkgagewhitt**
### What does this PR do, or why is it needed?

Adds a soft ask for enabling notifications. This should fix an issue where after rejecting notifications, the "enable notifications" button did nothing and could be confusing.

The soft ask checks that a user has been prompted, then if so, uses an alert to ask the user to enable notifications. If they accept, then the user will be routed to the app settings to enable notifications.

This soft ask will ONLY occur if the user has been previously hard asked AND they press the "Enable Notifications" button in onboarding.

### How do I test this PR?

1. In onboarding tap Enable Notifications and reject the hard ask
2. Log out
3. In onboarding tap Enable notifications; you should receive a soft ask
4. Reject it; nothing should happen
5. In onboarding tap Enable notifications; you should receive a soft ask
6. Accept it and turn your notifications on
7.  Return to the app; the state should be updated to reflect the change

## SCREENSHOTS

Screen Shot 2019-11-20 at 4 05 25 PM

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
🙌

**Comment by erikkgagewhitt** [comment]
Still one thing to work out, but once I've got that, it should be ready.

**Comment by erikkgagewhitt** [comment]
I think I have to scrap this. I cannot find a way to change the subscription status setting.

After lunch, I'm gonna toss this and simply disable the button as well as enabling the primary button and disabling the secondary (finish and skip respectively)

**Comment by erikkgagewhitt** [comment]
Closed in favor of https://github.com/ApollosProject/apollos-prototype/pull/1246

**Pull request closed without merging**
