### PR TITLE
Corrects the coordinates being sent to LocationFinder query

### PR DESCRIPTION
**Pull request by cdanwards**
### What does this PR do, or why is it needed?

Currently, the query in the locationfinder is passing the wrong coordinates for our campusCard list. It's sending the `initialRegion` which is set to be somewhere in Kansas(I think?) for the US map. This PR changes the coordinates to the User's coordinates so that the distance to location is correct.

### What design trade-offs/decisions were made?

I've set the default coordinates as the differential office in Cincinnati. This can be anything though.

### How do I test this PR?

Navigate to the Location in the user-settings and make sure the distance to location is correct. Or go through onboarding and do the same.

### What automated tests did you write?

N/A.

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@cdanwards Could you post a short screenshot or `gif` of this PR working?

**Comment by cdanwards** [comment]
Before:
Screen Shot 2019-06-09 at 9 10 55 AM

After:
Screen Shot 2019-06-09 at 9 08 08 AM

True Distance:
Screen Shot 2019-06-09 at 9 14 12 AM

😛

**Comment by vinnyjth** [comment]
THANK YOU! I'll admit I was totally confused because I thought you were solving a different problem in this PR. Your screenshots really helped clarify.  I'll review it soon and merge it. Thanks @cdanwards!

**Comment by vinnyjth** [comment]
I added some improvements so that the math behind scrolling from campus to campus is handled by the `MapView` and is now animated.

**Pull request merged**
