### PR TITLE
Adds Redis Cache and stores isLiked / likeCount in RedisCache. 

### PR DESCRIPTION
**Pull request by vinnyjth**
### What does this PR do, or why is it needed?

- Provides a connector to Redis for storing data to improve performance. 
- Implements the connector for the following module, caches the `likeCount` and `isLiked` for content items. Should improve performance dramatically on the home feed and discover feed.

### What design trade-offs/decisions were made?

n/a

### How do I test this PR?

- Open the app to the home feed with redis running.
- Note the number of calls to the `following` endpoint
- Reload the page, you will see that there are no calls to the `following` endpoint in your server console the second time. 
- Like an item, and make sure the like persists. 
- Unlike an item, and make sure the unlike persists. 

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
>  Is this redis cache connector also compatible to use as a Apollos Data Source cache?

Yes, it is :) Because it's easy to access from other `dataSources`. I could have implemented it as a `Model`, but I've been making everything `dataSources` by default because it fits better inside the Apollos Ecoystem.

**Comment by vinnyjth** [comment]
@conrad-vanl waiting on you to see my reply to your comment and respond before I merge this.

**Comment by conrad-vanl** [comment]
@vinnyjth this can be merged, more of a question of why it's not hooked up as the default cache for `Apollos`, whether we should or not vs the in-memory cache we're using.

**Comment by vinnyjth** [comment]
Big difference between this and the `in-memory cache` is this can store arbitrary computed data, and I can edit the cache easily. For example, with this cache, I can invalidate/fix the `likeCount` or `isLiked` of something when it's liked or unliked. 

The `in-memory-cache` is a straight up replay of the requests that were made, so we don't have much control over fixing/nuking/update the cache. So I think the answer is "both and"

**Pull request merged**
