### PR TITLE
adds a `ui-media-player-youtube` package

### PR DESCRIPTION
**Pull request by conrad-vanl**
## DESCRIPTION

😬

image

image

image

### What does this PR do, or why is it needed?

Adds a youtube package for our media-player. I've done everything I can do circumvent/cover up the youtube player controls, and overall this seems to work pretty well, atleast on iOS. I have not tested on Android yet, although I did write some of the basic handlers for it.

This is needed because of Willow's desire to utilize Youtube on their app, even if it means pushing people out to the Youtube app (which is something we could do currently without any core changes).

FWIW, I do not believe this PR should be merged. Instead, the `ui-media-player-youtube` package should be moved into Willow's repo, but there are a few (minor) core changes needed to make our media player extensible like this.

## TODO:

- [ ] TEST ON ANDROID. I wrote the basic handlers but have not booted an android sim up yet (need to hook up my mac mini)
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@burkeshartsis @vinnyjth I fixed youtube support by switching youtube libraries and updating our project to AndroidX compatibility. Once we update to RN 0.60 we'll have to move to AndroidX anyways, and it was a pretty simple add here to get working.

During the standup call today, I confirmed that we will NOT be merging this PR, but with y'alls blessing, I'd like to open a separate PR that picks the changes to `packages/apollos-ui-media-player` from this PR and merge that into core. Then, we can publish this youtube package within the Willow Creek ecosystem.

**Comment by vinnyjth** [comment]
@conrad-vanl are you thinking that you _will not_ be migrating core to AndroidX but rather migrating just willow, and then the changes merged here would be the changes the media-player package?

**Comment by conrad-vanl** [comment]
Good question. I’d like to migrate to RN 60 when we can, these native changes we will have to make when we do that anyways. So up to you I guess.

**Comment by vinnyjth** [comment]
> Good question. I’d like to migrate to RN 60 when we can, these native changes we will have to make when we do that anyways. So up to you I guess.

This is a tough choice to make. Changes like this are traditionally the hardest ones to make, either manually or with the upgrade tool. *I would prefer to bundle these as part of a "v60" upgrade, and then migrate Willow manually for now*. I did that for the 59 upgrade, essentially using Willow as a guinea pig for the upgrade, moving it ahead of core and seeing how it went, and I think we can do the same thing here for AndroidX.

**Comment by conrad-vanl** [comment]
Closing in favor of #865

**Pull request closed without merging**
