### PR TITLE
Polishes Profile fields based on QA Feedback

### LINKED ISSUE #386: User Avatar default image
## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_

> "profile image isn't tappable if there is no current image. "Change Photo" text is tappable. We need a placeholder image for accounts with no image (especially for new accounts were the UX is important)." – @burkeshartsis 

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

### LINKED ISSUE #387: Profile Tab nic-name [object Object]
## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details

> "Easy to reproduce by signing up for new account" – @conrad-vanl 

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

### PR DESCRIPTION
**Pull request by vinnyjth**
## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes #387 
- [ ] Closes #386 
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
screenshot 2018-11-05 09 53 38
screenshot 2018-11-05 09 31 31
screenshot 2018-11-05 15 04 01

**Comment by vinnyjth** [comment]
@burkeshartsis couldn't get the native tap to fill in the circle, still shows up as a square :/

**Comment by burkeshartsis** [comment]
@vinnyjth the ripple was fixed in #416 all you have to do is add a `borderRadius` prop equal to the size of your avatar 💥

**Pull request merged**
