### PR TITLE
Improved Caching of Content

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

Content was never being updated after the initial pull. This fixes that.

### What design trade-offs/decisions were made?

More data calls.

### How do I test this PR?

- look at some content
- update some content
- look at it again

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
Looks good to me.

**Comment by vinnyjth** [comment]
image

**Comment by vinnyjth** [comment]
@redreceipt I don't for the life of me understand why this is failing. If we can figure out how to resolve this error, I'm fine merging this.

**Comment by redreceipt** [comment]
I'm gonna take a look at fixing this again, this is a really crappy bug. Currently, once you get content one time, it's never updated again.

**Comment by vinnyjth** [comment]
@conrad-vanl @redreceipt Tests are still failing, would love to merge this but need to fix tests first :/

**Comment by redreceipt** [comment]
I know why this one is failing. the middle test is the exact same as the first but the mock has already been used. removing it.

**Comment by redreceipt** [comment]
nope, not true. didn't help.

**Comment by redreceipt** [comment]
`DevotionalContentItem` and its tests are a mess. It hasn't been updated since last year and the current snapshots don't make any sense. Maybe fixing those would help this test pass?

**Comment by redreceipt** [comment]
ok tests are fixed, please look over the latest changes before merging this, want to make sure I'm not missing anything.

FYI with the current state of things, I could technically add a merge label myself and it would auto-merge but I'm being cautious. We should be very careful with this mergify rule.

**Comment by redreceipt** [comment]
maybe we should dismiss stale reviews?

**Pull request merged**
