### PR TITLE
Installs Pods Automatically

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

Adds a script that updates and installs pods post `yarn install`

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@redreceipt I apperciate you putting this together. I have some concerns around if this is actually needed, and at present an approach like this will give us trouble in Travis and AppCenter (Travis shouldn't be installing pods, and AppCenter already installs pods via an automatic process).  I won't close this yet though, because I would love feedback from your team about what issues they have ran into with `Pods` thus far (if any) @richarddubay @cdanwards

**Comment by redreceipt** [comment]
what about if I just created a `yarn pods` that could still be abstracted so people wouldn't have to remember about pods but wouldn't get hung up in our other environments

**Comment by vinnyjth** [comment]
> what about if I just created a yarn pods that could still be abstracted so people wouldn't have to remember about pods but wouldn't get hung up in our other environments

This would be the best. In my head, a `yarn pods` would do this: 

1. check to see if you are using the same version of coocapods in the podfile.lock, warn you otherwise. 
2. Make sure your pod repo is up to date.
3. cd ios && pod install 

How does that sound?

**Comment by redreceipt** [comment]
@vinnyjth ok check this out

**Pull request merged**
