### PR TITLE
Use apollos plugin to fix max node issues

### LINKED ISSUE #729: Content with 20+ Children Don't Show
### Details

When we query Rock for content with 20+ children, it errors out because we hit the maximum number of nodes that can be returned.

**Request**

`https://alpha-rock.newspring.cc/api/ContentChannelItems?$filter=((Id%20eq%205281)%20or%20(Id%20eq%205282)%20or%20(Id%20eq%205283)%20or%20(Id%20eq%205284)%20or%20(Id%20eq%205285)%20or%20(Id%20eq%205286)%20or%20(Id%20eq%205287)%20or%20(Id%20eq%205288)%20or%20(Id%20eq%205289)%20or%20(Id%20eq%205290)%20or%20(Id%20eq%205291)%20or%20(Id%20eq%205292)%20or%20(Id%20eq%205293)%20or%20(Id%20eq%205294)%20or%20(Id%20eq%205295)%20or%20(Id%20eq%205296)%20or%20(Id%20eq%205297)%20or%20(Id%20eq%205298)%20or%20(Id%20eq%205299)%20or%20(Id%20eq%205300)%20or%20(Id%20eq%205301)%20or%20(Id%20eq%205302)%20or%20(Id%20eq%205303)%20or%20(Id%20eq%205304)%20or%20(Id%20eq%205305)%20or%20(Id%20eq%205306)%20or%20(Id%20eq%205307)%20or%20(Id%20eq%205308))%20and%20(((StartDateTime%20lt%20datetime'2019-05-17T10%3A07%3A46')%20or%20(StartDateTime%20eq%20null))%20and%20((ExpireDateTime%20gt%20datetime'2019-05-17T10%3A07%3A46')%20or%20(ExpireDateTime%20eq%20null))%20)`

**Error**

`"Message": "The query specified in the URI is not valid. The node count limit of '100' has been exceeded. To increase the limit, set the 'MaxNodeCount' property on EnableQueryAttribute or ODataValidationSettings."`

### Expected Behavior

Content with lots of children should show up.

### Actual Behavior

They don't.

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

Query this against alpha-rock.newspring.cc

```
# Write your query or mutation here
query getHorizontalContent {
  node(id: "ContentSeriesContentItem:e45f8b6bd534e0bbe4971f981adb71d6") {
    ... on ContentItem {
      id
      childContentItemsConnection {
        edges {
          node {
            id
            coverImage {
              name
              sources {
                uri
                __typename
              }
              __typename
            }
            parentChannel {
              id
              name
              iconName
              __typename
            }
            title
            sharing {
              url
              message
              title
              __typename
            }
            __typename
          }
          __typename
        }
        __typename
      }
      siblingContentItemsConnection {
        edges {
          node {
            id
            coverImage {
              name
              sources {
                uri
                __typename
              }
              __typename
            }
            parentChannel {
              id
              name
              iconName
              __typename
            }
            title
            sharing {
              url
              message
              title
              __typename
            }
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}
```

1.  first...
2.
3.
4.

### Stack Trace

</details>

### PR DESCRIPTION
**Pull request by vinnyjth**
### What does this PR do, or why is it needed?

Gets around a common OData node limit issue by using a custom (filterable) endpoint when fetching more than one item. This should have no change in API functionality, besides queries that currently error out, _not_ erroring out. 

### What design trade-offs/decisions were made?

n/a

### How do I test this PR?

1. Open up a series with more than 10 (or so) children.
2. Visit one of the children
3. The child should have their siblings listed below the content fold.

### What automated tests did you write?

Tests over new functionality.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes #729
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
Hold off on merging until I figure out why my coverage went down.

**Comment by redreceipt** [comment]
can't currently build this PR...

Screen Shot 2019-09-09 at 3 22 45 PM

**Comment by redreceipt** [comment]
I'm getting a graphql error on the 6th one in the psalms study
Screen Shot 2019-09-09 at 4 17 45 PM

**Comment by vinnyjth** [comment]
@redreceipt Not seeing that error. Can you try and give me the specific error that's occurring? Or reproduce in GraphiQL? 

image

@richarddubay you are also welcome to review this please :)

**Comment by redreceipt** [comment]
yep tried it again, seems to be good now

**Comment by richarddubay** [comment]
@vinnyjth First of all, the fact that you got it to load items when there is more than 20 things is awesome! Question: should this work for any number of content items? The Psalm devo series has 28 items, but it stops at 20.

**Comment by vinnyjth** [comment]
@richarddubay Should work for 50+ items! Not sure why we're not seeing more than 20, let me investigate.

**Comment by vinnyjth** [comment]
@richarddubay Looks like we are paginating the results right now, so as not to load too many at once :) We can create another PR to make sure scrolling to the end of the feed loads additional items.

**Comment by richarddubay** [comment]
@vinnyjth Okay, sweet. As long as that's on the radar, I'm good with this one.

**Comment by redreceipt** [comment]
want me to do it or are you starting work on it?

**Pull request merged**
