### PR TITLE
Allows Username Login

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

Screen Shot 2019-08-14 at 11 01 17 AM

### What does this PR do, or why is it needed?

This allows a user to login with a non-email string.

### What design trade-offs/decisions were made?

Navigating to `Auth` via `navigate` instead of `push`, seems to be fine. 🤷‍♂️

### How do I test this PR?

Change the value to false in the `NavigationService` and make sure you can login via username.

### What automated tests did you write?

None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@redreceipt I hate to hold this up further, but I've got a change I would like to suggest. 

Rather than passing down an `emailRequired` prop, have you considered passing down the `yup` `schema` instead? 

https://github.com/ApollosProject/apollos-prototype/pull/997/files#diff-41184c938d6428c4a3fd38e40fd65ae4R12

That would give churches the flexibility to write exactly the requirements they desire for email login.

**Comment by redreceipt** [comment]
I don't hate it but I just don't think it's necessary. It's a more complicated API to understand than a simple boolean (could even be an environment variable) and I don't see many other use cases other than "email or not".

**Comment by redreceipt** [comment]
Would love to prove that out as a pain point instead of over-engineering. It's an easy add down the road.

**Comment by vinnyjth** [comment]
Fine by me. Let's pair on a better way to pass down that "emailRequired" prop.

**Pull request merged**
