### PR TITLE
Fix passes by locking down version of PassKit node module

### LINKED ISSUE #795: Add to Apple Wallet Broken
### Details

Can't add the check-in barcode to Apple Wallet, just spins.

ezgif com-video-to-gif

### Expected Behavior

Should add the barcode to the Apple Wallet.

### Actual Behavior

The icon just spins and doesn't do anything.

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

### LINKED ISSUE #796: [Use] URL Slug code that NS developed in core
### User Story

As a user, I should get links to content on the web when I share content in the app.

### Description
Newspring developed a strategy for integrating the slugs + content channels in Rock to create a Permalink. We should consult @richarddubay and port this functionality to Core . 

### Acceptance Criteria

* [ ] It should [SPEC_DETAIL]

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

### PR DESCRIPTION
**Pull request by vinnyjth**
### What does this PR do, or why is it needed?

The version of the node passkit module we were using updated and thus broke our passkit integration (we reply extensively on internal APIs so we can use Rock templates) 

By locking to a version I know works, we can avoid future issues, and in the future come up with a better solution.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes #795
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
@vinnyjth is there something special I have to do to make my sim capable?

**Comment by vinnyjth** [comment]
@redreceipt Nope ... did you `yarn install`?

**Comment by redreceipt** [comment]
I did. Do I need to relink or something?

**Comment by redreceipt** [comment]
...or `pod install`?

**Comment by vinnyjth** [comment]
Nope... it should be all changes on the server. No client changes were needed.

**Comment by vinnyjth** [comment]
Can you open the `debugger tools` and try with the debug tools open?

**Comment by redreceipt** [comment]
Screen Shot 2019-06-17 at 4 52 14 PM
Screen Shot 2019-06-17 at 4 52 21 PM

**Comment by vinnyjth** [comment]
Turn off your `network inspect` please :)

**Comment by redreceipt** [comment]
my network inspect is not currently enabled

Screen Shot 2019-06-17 at 5 01 54 PM

**Pull request merged**
