### PR TITLE
Updates Jest and Lerna

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

This updates Jest and Lerna in order to fix a handlebars security vulnerability.

### What design trade-offs/decisions were made?

None.

### How do I test this PR?

None.

### What automated tests did you write?

None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
blocked by https://github.com/conventional-changelog/conventional-changelog/issues/474

**Comment by redreceipt** [comment]
The purpose of this one was to fix a security vulnerability in `handlebars`, just FYI

**Comment by conrad-vanl** [comment]
We'll scope this during the QA sprint

**Comment by redreceipt** [comment]
wouldn't be upset by just deleting this one, it was simply to fix a security vulnerability.

**Pull request closed without merging**
