### PR TITLE
Adds custom theme scaffolding

### PR DESCRIPTION
**Pull request by burkeshartsis**
## DESCRIPTION
This PR is an extension to #735 and while minimally functional on its own should be merged after it.

### What does this PR do, or why is it needed?
This establishes a `/theme` directory in the church/organization specific package (e.g. `apolloschurchapp`) and provides some structure to a few areas of app customization that will likely continue to grown and evolve. One of my favorite parts about what I am purposing in this PR is that we effectively are establishing and modeling the same folder structure as `/apollos-ui-kit/src/theme` but in app package. This should help provide guidance and understanding as to how this all works by having a strong example in `/apollos-ui-kit`.

##### Here is what happened
- the ui-kit `/icons` directory, where specific icon components (e.g. `BrandIcon`) live, is now in the `/apollos-ui-kit/src/theme` directory.
- custom icons follow the same paradigm above in `/apolloschurchapp/src/theme/icons`
- a custom theme definition now live in `/apolloschurchapp/src/theme` as well.
- an empty and well documented example `theme.js` is provided and already imported in `Providers` and passed into the `themeInput`. Providing custom theme attributes is a one step, plug-n-play, turn key, simplistic buzz word analogy process.
- custom icons are pre-configured the same as above. Just put them in the `icons` directory and export them from the `index` 💥

### What design trade-offs/decisions were made?
🤷‍♂

### How do I test this PR?
`yarn start` make sure nothing is broken and things look right. Add an icon component to the folder or add some custom theme definitions if you want but there are snapshot test that cover both of these situations already.

### What automated tests did you write?
None. Everything that was testable was already covered.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Partial work towards #558 
- [x] No new warnings in tests, in storybook, and in-app
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by burkeshartsis** [comment]
@conrad-vanl I'm curious on your thoughts on this but happy if you are ok with deferring to @vinnyjth's opinions.

**Comment by conrad-vanl** [comment]
@burkeshartsis are the core icons always available even if the user provides a different icon set?

If not....we could run into an issue where a core component relies on an icon that doesn't exist in the church's custom icons...

**Comment by burkeshartsis** [comment]
@conrad-vanl Great question and yes! So the core icons are always available and you can add any additional icons you want. If you add an icon of the same name it will override the core icon like my example able for `BrandIcon`.

**Comment by conrad-vanl** [comment]
@burkeshartsis looks like a circular import issue. Which is super unreliable right now. I’ve had similar issues like this before

**Pull request merged**
