### PR TITLE
Update onesignal

### LINKED ISSUE #817: Update react-native-onesignal
### User Story

As a developer, I want to make sure the native Android files aren't outdated

### Description

`react-native-onesignal` is using old syntax that was supposed to already have been removed (`compile` changed to `implementation`) guessing it's resolved by simply updating the npm package.

Screen Shot 2019-06-24 at 4 12 25 PM

### Why

So it doesn't randomly stop working one day.

### Acceptance Criteria

* [ ] It should update `react-native-signal` so Android Studio warnings go away
* [ ] `react-native-screens` too

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

### PR DESCRIPTION
**Pull request by vinnyjth**
## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes #817  
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
The reason I created this issue is so the warning in the gradle file would go away in hopes that compile was changed to implementation but it doesn't look like that was the case. Did you run react native Link?

**Comment by vinnyjth** [comment]
Yah I did @redreceipt. Can you paste the warning in the gradle file here? I wonder it's the underlying `Onesignal-Android` package

**Comment by redreceipt** [comment]
Yeah it probably is but if they haven't updated their Gradle file on the
latest version, maybe I should just do a bug report with them. The
screenshot is in the original issue I made.

https://github.com/ApollosProject/apollos-prototype/issues/817

--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599

**Comment by vinnyjth** [comment]
@redreceipt According to this, the newest version of OneSignal, the one we are using, uses `implementation` instead of `compile. 

https://github.com/geektimecoil/react-native-onesignal/blob/3.2.14/android/build.gradle#L21

**Comment by redreceipt** [comment]
very weird, guess I don't fully understand how those gradle files get updated...

**Comment by vinnyjth** [comment]
@redreceipt When running this PR, after `yarning`, I see this: 

image

**Comment by redreceipt** [comment]
haha my bad, I thought gradle files were in the repo for some reason. Approved :)

**Pull request merged**
