### PR TITLE
Fixes HTMLView content rendering bugs

### LINKED ISSUE #996: Need catch for incorrectly formatted content
### Details

If a Rock user doesn't correctly input content into the CMS system, sometimes it can have unintended consequences in the app.

Screen Shot 2019-08-13 at 4 22 39 PM

### Expected Behavior

Content should display as intended, with some catches when the input is slightly off.

### Actual Behavior

Content isn't formatted as intended if tags are left off in the content input on Rock. 
Screenshot above is missing a `<p>` wrapper.

### Possible Fix

Check to see if text is outside the bounds of wrapping tags and add one if so.

### PR DESCRIPTION
**Pull request by burkeshartsis**
## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes #996 
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [x] Manual QA on iOS and ensure it looks/behaves as expected
- [x] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [x] Read through the "Files changed" tab _very carefully_
- [x] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
Do we have a proposed direction on solving this? I appreciate having a story with bad HTML. Any way I can help out?

**Comment by burkeshartsis** [comment]
@conrad-vanl wanted to look at this.

**Comment by conrad-vanl** [comment]
Oh hai Mark! I knew there was a PR I said I'd look at. 👀 on this today.

**Comment by conrad-vanl** [comment]
@vinnyjth @burkeshartsis @richarddubay here's a video explaining what I did in the last commit, and comparisons to the NewSpring website:

https://www.loom.com/share/50a7cc404c8e47d8b77dd66dea04de77

Let me know thoughts on this.

**Comment by burkeshartsis** [comment]
@conrad-vanl alright so I think Rock's WYSIWYG editor is probably where the `div`s are getting added. It's also what inserts the `br` tags. I forget why exactly we were stripping `div` tags from content but I remember that we had a reason. Maybe there is something in the commit history that could speak to it.

**Comment by conrad-vanl** [comment]
ahhh

**Comment by conrad-vanl** [comment]
it's happening here https://github.com/ApollosProject/apollos-prototype/blob/master/packages/apollos-data-connector-rock/src/content-items/resolver.js#L15

**Comment by conrad-vanl** [comment]
https://github.com/ApollosProject/apollos-prototype/blob/master/packages/apollos-data-connector-rock/src/sanitize-html.js

**Comment by conrad-vanl** [comment]
Ok so I guess we could add `div` in as an allowed tag, and then fix the renderer to support divs

**Comment by conrad-vanl** [comment]
I think the renderer method would just be:

```
case 'div':
  return <View>{wrapTextChildren(children)}</View>;
```

**Comment by conrad-vanl** [comment]
In the loom video I think I missed the `wrapTextChildren` bit

**Comment by conrad-vanl** [comment]
@burkeshartsis this should be g2g now. Recorded another video walkthrough of the changes:

https://www.loom.com/share/27800ff46e8e420099e4b30d9161e86f

@vinnyjth there was some odd snapshot changes that my machine picked up, that I guess travis is failing on. Any ideas?

**Comment by vinnyjth** [comment]
@conrad-vanl @burkeshartsis Picked up that snapshot change for a bit, and then it stopped happening for him. It's somehow related to `redis`, I would recommend not committing it.

**Comment by conrad-vanl** [comment]
@vinnyjth is it just me, I can't find a FAIL in that travis build?

**Comment by vinnyjth** [comment]
You had some dates change in the onboarding connected components 🤔

**Comment by richarddubay** [comment]
@conrad-vanl This all seems like pretty genius work to me! Also, the videos were _super_ helpful. Things are starting to look really great! 👍

**Comment by conrad-vanl** [comment]
@vinnyjth I know! I didn't touch any of that though ...

**Comment by conrad-vanl** [comment]
> @conrad-vanl This all seems like pretty genius work to me! Also, the videos were super helpful. Things are starting to look really great! 👍

@richarddubay thanks! It's my new favorite thing to do with PRs. I'd encourage others to do it too 😀

**Comment by burkeshartsis** [comment]
> @conrad-vanl @burkeshartsis Picked up that snapshot change for a bit, and then it stopped happening for him. It's somehow related to redis, I would recommend not committing it.

@vinnyjth I actually still get this snapshot every time I run tests 😞

**Comment by vinnyjth** [comment]
@burkeshartsis Gotcha. Let's not include the change in this PR and then we can figure out why it
s different for us at some point. The correct value seems to be whatever passes in travis, which is not this change.

**Comment by vinnyjth** [comment]
❤️ ❤️ ❤️ ❤️

**Pull request merged**
